"""
Device Fingerprinting Module for Artemis
Identifies device types from MAC address, open ports, and service signatures.
"""

import asyncio
import socket
import struct
from typing import Optional
from dataclasses import dataclass


@dataclass
class DeviceFingerprint:
    """Device fingerprint result."""
    device_type: str
    vendor: str
    model: str = ""
    confidence: float = 0.0
    services: list = None
    
    def __post_init__(self):
        if self.services is None:
            self.services = []


# =============================================================================
# COMPREHENSIVE MAC OUI DATABASE
# =============================================================================

MAC_VENDORS = {
    # Apple devices
    "00-03-93": ("Apple", "apple"),
    "00-05-02": ("Apple", "apple"),
    "00-0A-27": ("Apple", "apple"),
    "00-0A-95": ("Apple", "apple"),
    "00-0D-93": ("Apple", "apple"),
    "00-10-FA": ("Apple", "apple"),
    "00-11-24": ("Apple", "apple"),
    "00-14-51": ("Apple", "apple"),
    "00-16-CB": ("Apple", "apple"),
    "00-17-F2": ("Apple", "apple"),
    "00-19-E3": ("Apple", "apple"),
    "00-1B-63": ("Apple", "apple"),
    "00-1C-B3": ("Apple", "apple"),
    "00-1D-4F": ("Apple", "apple"),
    "00-1E-52": ("Apple", "apple"),
    "00-1E-C2": ("Apple", "apple"),
    "00-1F-5B": ("Apple", "apple"),
    "00-1F-F3": ("Apple", "apple"),
    "00-21-E9": ("Apple", "apple"),
    "00-22-41": ("Apple", "apple"),
    "00-23-12": ("Apple", "apple"),
    "00-23-32": ("Apple", "apple"),
    "00-23-6C": ("Apple", "apple"),
    "00-23-DF": ("Apple", "apple"),
    "00-24-36": ("Apple", "apple"),
    "00-25-00": ("Apple", "apple"),
    "00-25-4B": ("Apple", "apple"),
    "00-25-BC": ("Apple", "apple"),
    "00-26-08": ("Apple", "apple"),
    "00-26-4A": ("Apple", "apple"),
    "00-26-B0": ("Apple", "apple"),
    "00-26-BB": ("Apple", "apple"),
    "00-30-65": ("Apple", "apple"),
    "00-3E-E1": ("Apple", "apple"),
    "00-50-E4": ("Apple", "apple"),
    "00-56-CD": ("Apple", "apple"),
    "00-61-71": ("Apple", "apple"),
    "00-6D-52": ("Apple", "apple"),
    "00-88-65": ("Apple", "apple"),
    "00-B3-62": ("Apple", "apple"),
    "00-C6-10": ("Apple", "apple"),
    "00-CD-FE": ("Apple", "apple"),
    "00-DB-70": ("Apple", "apple"),
    "00-F4-B9": ("Apple", "apple"),
    "00-F7-6F": ("Apple", "apple"),
    "04-0C-CE": ("Apple", "apple"),
    "04-15-52": ("Apple", "apple"),
    "04-1B-BA": ("Apple", "apple"),
    "04-26-65": ("Apple", "apple"),
    "04-4B-ED": ("Apple", "apple"),
    "04-52-F3": ("Apple", "apple"),
    "04-54-53": ("Apple", "apple"),
    "04-69-F8": ("Apple", "apple"),
    "04-D3-CF": ("Apple", "apple"),
    "04-DB-56": ("Apple", "apple"),
    "04-E5-36": ("Apple", "apple"),
    "04-F1-3E": ("Apple", "apple"),
    "04-F7-E4": ("Apple", "apple"),
    "08-00-07": ("Apple", "apple"),
    "08-66-98": ("Apple", "apple"),
    "08-6D-41": ("Apple", "apple"),
    "08-70-45": ("Apple", "apple"),
    "08-74-02": ("Apple", "apple"),
    "0C-4D-E9": ("Apple", "apple"),
    "0C-74-C2": ("Apple", "apple"),
    "0C-77-1A": ("Apple", "apple"),
    "10-1C-0C": ("Apple", "apple"),
    "10-40-F3": ("Apple", "apple"),
    "10-41-7F": ("Apple", "apple"),
    "10-94-BB": ("Apple", "apple"),
    "10-9A-DD": ("Apple", "apple"),
    "10-DD-B1": ("Apple", "apple"),
    "14-10-9F": ("Apple", "apple"),
    "14-5A-05": ("Apple", "apple"),
    "14-8F-C6": ("Apple", "apple"),
    "14-99-E2": ("Apple", "apple"),
    "18-20-32": ("Apple", "apple"),
    "18-34-51": ("Apple", "apple"),
    "18-65-90": ("Apple", "apple"),
    "18-81-0E": ("Apple", "apple"),
    "18-9E-FC": ("Apple", "apple"),
    "18-AF-61": ("Apple", "apple"),
    "18-AF-8F": ("Apple", "apple"),
    "18-E7-F4": ("Apple", "apple"),
    "18-EE-69": ("Apple", "apple"),
    "1C-1A-C0": ("Apple", "apple"),
    "1C-36-BB": ("Apple", "apple"),
    "1C-5C-F2": ("Apple", "apple"),
    "1C-91-48": ("Apple", "apple"),
    "1C-AB-A7": ("Apple", "apple"),
    "1C-E6-2B": ("Apple", "apple"),
    "20-3C-AE": ("Apple", "apple"),
    "20-78-F0": ("Apple", "apple"),
    "20-7D-74": ("Apple", "apple"),
    "20-9B-CD": ("Apple", "apple"),
    "20-A2-E4": ("Apple", "apple"),
    "20-AB-37": ("Apple", "apple"),
    "20-C9-D0": ("Apple", "apple"),
    "24-1E-EB": ("Apple", "apple"),
    "24-24-0E": ("Apple", "apple"),
    "24-5B-A7": ("Apple", "apple"),
    "24-A0-74": ("Apple", "apple"),
    "24-A2-E1": ("Apple", "apple"),
    "24-AB-81": ("Apple", "apple"),
    "24-E3-14": ("Apple", "apple"),
    "24-F0-94": ("Apple", "apple"),
    "24-F6-77": ("Apple", "apple"),
    "28-0B-5C": ("Apple", "apple"),
    "28-37-37": ("Apple", "apple"),
    "28-56-5A": ("Apple", "apple"),
    "28-5A-EB": ("Apple", "apple"),
    "28-6A-B8": ("Apple", "apple"),
    "28-6A-BA": ("Apple", "apple"),
    "28-A0-2B": ("Apple", "apple"),
    "28-CF-DA": ("Apple", "apple"),
    "28-CF-E9": ("Apple", "apple"),
    "28-E0-2C": ("Apple", "apple"),
    "28-E1-4C": ("Apple", "apple"),
    "28-E7-CF": ("Apple", "apple"),
    "28-ED-E0": ("Apple", "apple"),
    "28-F0-76": ("Apple", "apple"),
    "2C-1F-23": ("Apple", "apple"),
    "2C-20-0B": ("Apple", "apple"),
    "2C-30-68": ("Apple", "apple"),
    "2C-33-61": ("Apple", "apple"),
    "2C-54-91": ("Apple", "apple"),
    "2C-B4-3A": ("Apple", "apple"),
    "2C-BE-08": ("Apple", "apple"),
    "2C-F0-A2": ("Apple", "apple"),
    "2C-F0-EE": ("Apple", "apple"),
    "30-35-AD": ("Apple", "apple"),
    "30-63-6B": ("Apple", "apple"),
    "30-90-AB": ("Apple", "apple"),
    "30-F7-C5": ("Apple", "apple"),
    "34-08-BC": ("Apple", "apple"),
    "34-12-98": ("Apple", "apple"),
    "34-15-9E": ("Apple", "apple"),
    "34-36-3B": ("Apple", "apple"),
    "34-51-C9": ("Apple", "apple"),
    "34-AB-37": ("Apple", "apple"),
    "34-C0-59": ("Apple", "apple"),
    "34-E2-FD": ("Apple", "apple"),
    "38-0F-4A": ("Apple", "apple"),
    "38-48-4C": ("Apple", "apple"),
    "38-53-9C": ("Apple", "apple"),
    "38-66-F0": ("Apple", "apple"),
    "38-71-DE": ("Apple", "apple"),
    "38-B5-4D": ("Apple", "apple"),
    "38-C9-86": ("Apple", "apple"),
    "38-CA-DA": ("Apple", "apple"),
    "3C-06-30": ("Apple", "apple"),
    "3C-07-71": ("Apple", "apple"),
    "3C-15-C2": ("Apple", "apple"),
    "3C-2E-F9": ("Apple", "apple"),
    "3C-2E-FF": ("Apple", "apple"),
    "3C-D0-F8": ("Apple", "apple"),
    "40-30-04": ("Apple", "apple"),
    "40-33-1A": ("Apple", "apple"),
    "40-3C-FC": ("Apple", "apple"),
    "40-4D-7F": ("Apple", "apple"),
    "40-6C-8F": ("Apple", "apple"),
    "40-83-1D": ("Apple", "apple"),
    "40-98-AD": ("Apple", "apple"),
    "40-A6-D9": ("Apple", "apple"),
    "40-B3-95": ("Apple", "apple"),
    "40-BC-60": ("Apple", "apple"),
    "40-C3-D7": ("Apple", "apple"),
    "40-CB-C0": ("Apple", "apple"),
    "40-D3-2D": ("Apple", "apple"),
    "44-00-10": ("Apple", "apple"),
    "44-2A-60": ("Apple", "apple"),
    "44-4C-0C": ("Apple", "apple"),
    "44-D8-84": ("Apple", "apple"),
    "44-FB-42": ("Apple", "apple"),
    "48-3B-38": ("Apple", "apple"),
    "48-43-7C": ("Apple", "apple"),
    "48-4B-AA": ("Apple", "apple"),
    "48-60-BC": ("Apple", "apple"),
    "48-74-6E": ("Apple", "apple"),
    "48-A1-95": ("Apple", "apple"),
    "48-BF-6B": ("Apple", "apple"),
    "48-D7-05": ("Apple", "apple"),
    "48-E9-F1": ("Apple", "apple"),
    "4C-32-75": ("Apple", "apple"),
    "4C-56-9D": ("Apple", "apple"),
    "4C-57-CA": ("Apple", "apple"),
    "4C-74-BF": ("Apple", "apple"),
    "4C-7C-5F": ("Apple", "apple"),
    "4C-8D-79": ("Apple", "apple"),
    "4C-AB-4F": ("Apple", "apple"),
    "50-7A-55": ("Apple", "apple"),
    "50-82-D5": ("Apple", "apple"),
    "50-A6-7F": ("Apple", "apple"),
    "50-BC-96": ("Apple", "apple"),
    "50-DE-06": ("Apple", "apple"),
    "50-EA-D6": ("Apple", "apple"),
    "54-26-96": ("Apple", "apple"),
    "54-33-CB": ("Apple", "apple"),
    "54-4E-90": ("Apple", "apple"),
    "54-72-4F": ("Apple", "apple"),
    "54-9F-13": ("Apple", "apple"),
    "54-AE-27": ("Apple", "apple"),
    "54-E4-3A": ("Apple", "apple"),
    "54-EA-A8": ("Apple", "apple"),
    "58-1F-AA": ("Apple", "apple"),
    "58-40-4E": ("Apple", "apple"),
    "58-55-CA": ("Apple", "apple"),
    "58-7F-57": ("Apple", "apple"),
    "58-B0-35": ("Apple", "apple"),
    "58-E2-8F": ("Apple", "apple"),
    "5C-59-48": ("Apple", "apple"),
    "5C-8D-4E": ("Apple", "apple"),
    "5C-95-AE": ("Apple", "apple"),
    "5C-96-9D": ("Apple", "apple"),
    "5C-97-F3": ("Apple", "apple"),
    "5C-F5-DA": ("Apple", "apple"),
    "5C-F7-E6": ("Apple", "apple"),
    "60-03-08": ("Apple", "apple"),
    "60-1D-91": ("Apple", "apple"),
    "60-30-D4": ("Apple", "apple"),
    "60-33-4B": ("Apple", "apple"),
    "60-69-44": ("Apple", "apple"),
    "60-8C-4A": ("Apple", "apple"),
    "60-92-17": ("Apple", "apple"),
    "60-A3-7D": ("Apple", "apple"),
    "60-C5-47": ("Apple", "apple"),
    "60-D9-C7": ("Apple", "apple"),
    "60-F4-45": ("Apple", "apple"),
    "60-F8-1D": ("Apple", "apple"),
    "60-FA-CD": ("Apple", "apple"),
    "60-FB-42": ("Apple", "apple"),
    "60-FE-C5": ("Apple", "apple"),
    "64-20-0C": ("Apple", "apple"),
    "64-4B-F0": ("Apple", "apple"),
    "64-70-33": ("Apple", "apple"),
    "64-76-BA": ("Apple", "apple"),
    "64-9A-BE": ("Apple", "apple"),
    "64-A3-CB": ("Apple", "apple"),
    "64-A5-C3": ("Apple", "apple"),
    "64-B0-A6": ("Apple", "apple"),
    "64-B9-E8": ("Apple", "apple"),
    "64-E6-82": ("Apple", "apple"),
    "68-09-27": ("Apple", "apple"),
    "68-5B-35": ("Apple", "apple"),
    "68-64-4B": ("Apple", "apple"),
    "68-96-7B": ("Apple", "apple"),
    "68-9C-70": ("Apple", "apple"),
    "68-A8-6D": ("Apple", "apple"),
    "68-AB-1E": ("Apple", "apple"),
    "68-AE-20": ("Apple", "apple"),
    "68-D9-3C": ("Apple", "apple"),
    "68-DB-CA": ("Apple", "apple"),
    "68-FB-7E": ("Apple", "apple"),
    "6C-19-C0": ("Apple", "apple"),
    "6C-40-08": ("Apple", "apple"),
    "6C-4D-73": ("Apple", "apple"),
    "6C-70-9F": ("Apple", "apple"),
    "6C-72-E7": ("Apple", "apple"),
    "6C-8D-C1": ("Apple", "apple"),
    "6C-94-F8": ("Apple", "apple"),
    "6C-96-CF": ("Apple", "apple"),
    "6C-AB-31": ("Apple", "apple"),
    "6C-C2-6B": ("Apple", "apple"),
    "70-11-24": ("Apple", "apple"),
    "70-14-A6": ("Apple", "apple"),
    "70-3E-AC": ("Apple", "apple"),
    "70-48-0F": ("Apple", "apple"),
    "70-56-81": ("Apple", "apple"),
    "70-73-CB": ("Apple", "apple"),
    "70-81-EB": ("Apple", "apple"),
    "70-A2-B3": ("Apple", "apple"),
    "70-CD-60": ("Apple", "apple"),
    "70-DE-E2": ("Apple", "apple"),
    "70-E7-2C": ("Apple", "apple"),
    "70-EC-E4": ("Apple", "apple"),
    "70-EF-00": ("Apple", "apple"),
    "70-F0-87": ("Apple", "apple"),
    "74-1B-B2": ("Apple", "apple"),
    "74-81-14": ("Apple", "apple"),
    "74-8D-08": ("Apple", "apple"),
    "74-E1-B6": ("Apple", "apple"),
    "74-E2-F5": ("Apple", "apple"),
    "78-31-C1": ("Apple", "apple"),
    "78-32-1B": ("Apple", "apple"),
    "78-3A-84": ("Apple", "apple"),
    "78-4F-43": ("Apple", "apple"),
    "78-67-D7": ("Apple", "apple"),
    "78-6C-1C": ("Apple", "apple"),
    "78-7E-61": ("Apple", "apple"),
    "78-88-6D": ("Apple", "apple"),
    "78-9F-70": ("Apple", "apple"),
    "78-A3-E4": ("Apple", "apple"),
    "78-CA-39": ("Apple", "apple"),
    "78-D7-5F": ("Apple", "apple"),
    "78-FD-94": ("Apple", "apple"),
    "7C-01-91": ("Apple", "apple"),
    "7C-04-D0": ("Apple", "apple"),
    "7C-11-BE": ("Apple", "apple"),
    "7C-50-49": ("Apple", "apple"),
    "7C-6D-62": ("Apple", "apple"),
    "7C-6D-F8": ("Apple", "apple"),
    "7C-9A-1D": ("Apple", "apple"),
    "7C-B7-7B": ("Apple", "apple"),
    "7C-C3-A1": ("Apple", "apple"),
    "7C-C5-37": ("Apple", "apple"),
    "7C-D1-C3": ("Apple", "apple"),
    "7C-E9-D3": ("Apple", "apple"),
    "7C-F0-5F": ("Apple", "apple"),
    "7C-FA-DF": ("Apple", "apple"),
    "80-00-6E": ("Apple", "apple"),
    "80-49-71": ("Apple", "apple"),
    "80-82-23": ("Apple", "apple"),
    "80-92-9F": ("Apple", "apple"),
    "80-B0-3D": ("Apple", "apple"),
    "80-BE-05": ("Apple", "apple"),
    "80-D6-05": ("Apple", "apple"),
    "80-E6-50": ("Apple", "apple"),
    "80-EA-96": ("Apple", "apple"),
    "80-ED-2C": ("Apple", "apple"),
    "84-29-99": ("Apple", "apple"),
    "84-38-35": ("Apple", "apple"),
    "84-78-8B": ("Apple", "apple"),
    "84-85-06": ("Apple", "apple"),
    "84-89-AD": ("Apple", "apple"),
    "84-8E-0C": ("Apple", "apple"),
    "84-A1-34": ("Apple", "apple"),
    "84-B1-53": ("Apple", "apple"),
    "84-FC-AC": ("Apple", "apple"),
    "84-FC-FE": ("Apple", "apple"),
    "88-1F-A1": ("Apple", "apple"),
    "88-53-95": ("Apple", "apple"),
    "88-63-DF": ("Apple", "apple"),
    "88-66-A5": ("Apple", "apple"),
    "88-6B-6E": ("Apple", "apple"),
    "88-C6-63": ("Apple", "apple"),
    "88-CB-87": ("Apple", "apple"),
    "88-E8-7F": ("Apple", "apple"),
    "8C-00-6D": ("Apple", "apple"),
    "8C-2D-AA": ("Apple", "apple"),
    "8C-58-77": ("Apple", "apple"),
    "8C-7B-9D": ("Apple", "apple"),
    "8C-7C-92": ("Apple", "apple"),
    "8C-85-90": ("Apple", "apple"),
    "8C-8E-F2": ("Apple", "apple"),
    "8C-FA-BA": ("Apple", "apple"),
    "90-27-E4": ("Apple", "apple"),
    "90-3C-92": ("Apple", "apple"),
    "90-60-F1": ("Apple", "apple"),
    "90-72-40": ("Apple", "apple"),
    "90-8D-6C": ("Apple", "apple"),
    "90-B0-ED": ("Apple", "apple"),
    "90-B2-1F": ("Apple", "apple"),
    "90-B9-31": ("Apple", "apple"),
    "90-C1-C6": ("Apple", "apple"),
    "90-FD-61": ("Apple", "apple"),
    "94-94-26": ("Apple", "apple"),
    "94-BF-2D": ("Apple", "apple"),
    "94-E9-6A": ("Apple", "apple"),
    "94-F6-A3": ("Apple", "apple"),
    "98-01-A7": ("Apple", "apple"),
    "98-03-D8": ("Apple", "apple"),
    "98-10-E8": ("Apple", "apple"),
    "98-46-0A": ("Apple", "apple"),
    "98-5A-EB": ("Apple", "apple"),
    "98-69-8A": ("Apple", "apple"),
    "98-B8-E3": ("Apple", "apple"),
    "98-CA-33": ("Apple", "apple"),
    "98-D6-BB": ("Apple", "apple"),
    "98-E0-D9": ("Apple", "apple"),
    "98-F0-AB": ("Apple", "apple"),
    "98-FE-94": ("Apple", "apple"),
    "9C-04-EB": ("Apple", "apple"),
    "9C-20-7B": ("Apple", "apple"),
    "9C-29-3F": ("Apple", "apple"),
    "9C-35-EB": ("Apple", "apple"),
    "9C-4F-DA": ("Apple", "apple"),
    "9C-84-BF": ("Apple", "apple"),
    "9C-8B-A0": ("Apple", "apple"),
    "9C-E3-3F": ("Apple", "apple"),
    "9C-F3-87": ("Apple", "apple"),
    "9C-FC-01": ("Apple", "apple"),
    "A0-18-28": ("Apple", "apple"),
    "A0-3B-E3": ("Apple", "apple"),
    "A0-4E-A7": ("Apple", "apple"),
    "A0-56-F3": ("Apple", "apple"),
    "A0-99-9B": ("Apple", "apple"),
    "A0-D7-95": ("Apple", "apple"),
    "A0-ED-CD": ("Apple", "apple"),
    "A4-5E-60": ("Apple", "apple"),
    "A4-67-06": ("Apple", "apple"),
    "A4-83-E7": ("Apple", "apple"),
    "A4-B1-97": ("Apple", "apple"),
    "A4-B8-05": ("Apple", "apple"),
    "A4-C3-61": ("Apple", "apple"),
    "A4-D1-8C": ("Apple", "apple"),
    "A4-D1-D2": ("Apple", "apple"),
    "A4-E9-75": ("Apple", "apple"),
    "A4-F1-E8": ("Apple", "apple"),
    "A8-20-66": ("Apple", "apple"),
    "A8-5B-78": ("Apple", "apple"),
    "A8-5C-2C": ("Apple", "apple"),
    "A8-66-7F": ("Apple", "apple"),
    "A8-86-DD": ("Apple", "apple"),
    "A8-8E-24": ("Apple", "apple"),
    "A8-96-8A": ("Apple", "apple"),
    "A8-BB-CF": ("Apple", "apple"),
    "A8-BE-27": ("Apple", "apple"),
    "A8-FA-D8": ("Apple", "apple"),
    "AC-1F-74": ("Apple", "apple"),
    "AC-29-3A": ("Apple", "apple"),
    "AC-3C-0B": ("Apple", "apple"),
    "AC-61-EA": ("Apple", "apple"),
    "AC-7F-3E": ("Apple", "apple"),
    "AC-87-A3": ("Apple", "apple"),
    "AC-BC-32": ("Apple", "apple"),
    "AC-CF-5C": ("Apple", "apple"),
    "AC-E4-B5": ("Apple", "apple"),
    "AC-FD-EC": ("Apple", "apple"),
    "B0-19-C6": ("Apple", "apple"),
    "B0-34-95": ("Apple", "apple"),
    "B0-65-BD": ("Apple", "apple"),
    "B0-70-2D": ("Apple", "apple"),
    "B0-9F-BA": ("Apple", "apple"),
    "B4-18-D1": ("Apple", "apple"),
    "B4-4B-D2": ("Apple", "apple"),
    "B4-8B-19": ("Apple", "apple"),
    "B4-9C-DF": ("Apple", "apple"),
    "B4-F0-AB": ("Apple", "apple"),
    "B4-F6-1C": ("Apple", "apple"),
    "B8-09-8A": ("Apple", "apple"),
    "B8-17-C2": ("Apple", "apple"),
    "B8-41-A4": ("Apple", "apple"),
    "B8-44-D9": ("Apple", "apple"),
    "B8-53-AC": ("Apple", "apple"),
    "B8-5A-F7": ("Apple", "apple"),
    "B8-63-4D": ("Apple", "apple"),
    "B8-78-2E": ("Apple", "apple"),
    "B8-8D-12": ("Apple", "apple"),
    "B8-C1-11": ("Apple", "apple"),
    "B8-C7-5D": ("Apple", "apple"),
    "B8-E8-56": ("Apple", "apple"),
    "B8-F6-B1": ("Apple", "apple"),
    "B8-FF-61": ("Apple", "apple"),
    "BC-3B-AF": ("Apple", "apple"),
    "BC-4C-C4": ("Apple", "apple"),
    "BC-52-B7": ("Apple", "apple"),
    "BC-54-36": ("Apple", "apple"),
    "BC-67-78": ("Apple", "apple"),
    "BC-6C-21": ("Apple", "apple"),
    "BC-92-6B": ("Apple", "apple"),
    "BC-9F-EF": ("Apple", "apple"),
    "BC-A9-20": ("Apple", "apple"),
    "BC-D1-1F": ("Apple", "apple"),
    "BC-EC-5D": ("Apple", "apple"),
    "BC-FE-D9": ("Apple", "apple"),
    "C0-1A-DA": ("Apple", "apple"),
    "C0-63-94": ("Apple", "apple"),
    "C0-84-7A": ("Apple", "apple"),
    "C0-9F-42": ("Apple", "apple"),
    "C0-A5-3E": ("Apple", "apple"),
    "C0-B6-58": ("Apple", "apple"),
    "C0-CC-F8": ("Apple", "apple"),
    "C0-CE-CD": ("Apple", "apple"),
    "C0-D0-12": ("Apple", "apple"),
    "C0-D3-C0": ("Apple", "apple"),
    "C0-F2-FB": ("Apple", "apple"),
    "C4-2C-03": ("Apple", "apple"),
    "C4-B3-01": ("Apple", "apple"),
    "C8-1E-E7": ("Apple", "apple"),
    "C8-2A-14": ("Apple", "apple"),
    "C8-33-4B": ("Apple", "apple"),
    "C8-69-CD": ("Apple", "apple"),
    "C8-6F-1D": ("Apple", "apple"),
    "C8-85-50": ("Apple", "apple"),
    "C8-B5-B7": ("Apple", "apple"),
    "C8-BC-C8": ("Apple", "apple"),
    "C8-D0-83": ("Apple", "apple"),
    "C8-E0-EB": ("Apple", "apple"),
    "C8-F6-50": ("Apple", "apple"),
    "CC-08-8D": ("Apple", "apple"),
    "CC-20-E8": ("Apple", "apple"),
    "CC-25-EF": ("Apple", "apple"),
    "CC-29-F5": ("Apple", "apple"),
    "CC-44-63": ("Apple", "apple"),
    "CC-78-5F": ("Apple", "apple"),
    "CC-C7-60": ("Apple", "apple"),
    "D0-03-4B": ("Apple", "apple"),
    "D0-25-98": ("Apple", "apple"),
    "D0-33-11": ("Apple", "apple"),
    "D0-4F-7E": ("Apple", "apple"),
    "D0-81-7A": ("Apple", "apple"),
    "D0-A6-37": ("Apple", "apple"),
    "D0-C5-F3": ("Apple", "apple"),
    "D0-E1-40": ("Apple", "apple"),
    "D4-61-9D": ("Apple", "apple"),
    "D4-9A-20": ("Apple", "apple"),
    "D4-DC-CD": ("Apple", "apple"),
    "D4-F4-6F": ("Apple", "apple"),
    "D8-00-4D": ("Apple", "apple"),
    "D8-1D-72": ("Apple", "apple"),
    "D8-30-62": ("Apple", "apple"),
    "D8-96-95": ("Apple", "apple"),
    "D8-9E-3F": ("Apple", "apple"),
    "D8-A2-5E": ("Apple", "apple"),
    "D8-BB-2C": ("Apple", "apple"),
    "D8-CF-9C": ("Apple", "apple"),
    "D8-D1-CB": ("Apple", "apple"),
    "DC-0C-5C": ("Apple", "apple"),
    "DC-2B-2A": ("Apple", "apple"),
    "DC-2B-61": ("Apple", "apple"),
    "DC-37-14": ("Apple", "apple"),
    "DC-41-5F": ("Apple", "apple"),
    "DC-56-E7": ("Apple", "apple"),
    "DC-86-D8": ("Apple", "apple"),
    "DC-9B-9C": ("Apple", "apple"),
    "DC-A4-CA": ("Apple", "apple"),
    "DC-D3-A2": ("Apple", "apple"),
    "DC-E5-5B": ("Apple", "apple"),
    "E0-5F-45": ("Apple", "apple"),
    "E0-66-78": ("Apple", "apple"),
    "E0-6F-D0": ("Apple", "apple"),
    "E0-AC-CB": ("Apple", "apple"),
    "E0-B5-2D": ("Apple", "apple"),
    "E0-B9-BA": ("Apple", "apple"),
    "E0-C7-67": ("Apple", "apple"),
    "E0-C9-7A": ("Apple", "apple"),
    "E0-F5-C6": ("Apple", "apple"),
    "E0-F8-47": ("Apple", "apple"),
    "E4-25-E7": ("Apple", "apple"),
    "E4-2B-34": ("Apple", "apple"),
    "E4-8B-7F": ("Apple", "apple"),
    "E4-98-D6": ("Apple", "apple"),
    "E4-9A-DC": ("Apple", "apple"),
    "E4-9A-79": ("Apple", "apple"),
    "E4-B2-FB": ("Apple", "apple"),
    "E4-C6-3D": ("Apple", "apple"),
    "E4-CE-8F": ("Apple", "apple"),
    "E4-E0-A6": ("Apple", "apple"),
    "E8-04-0B": ("Apple", "apple"),
    "E8-06-88": ("Apple", "apple"),
    "E8-80-2E": ("Apple", "apple"),
    "E8-8D-28": ("Apple", "apple"),
    "EC-35-86": ("Apple", "apple"),
    "EC-85-2F": ("Apple", "apple"),
    "F0-18-98": ("Apple", "apple"),
    "F0-24-75": ("Apple", "apple"),
    "F0-4F-7C": ("Apple", "apple"),
    "F0-79-60": ("Apple", "apple"),
    "F0-98-9D": ("Apple", "apple"),
    "F0-99-BF": ("Apple", "apple"),
    "F0-B0-E7": ("Apple", "apple"),
    "F0-C1-F1": ("Apple", "apple"),
    "F0-CB-A1": ("Apple", "apple"),
    "F0-D1-A9": ("Apple", "apple"),
    "F0-DB-E2": ("Apple", "apple"),
    "F0-DC-E2": ("Apple", "apple"),
    "F0-F6-1C": ("Apple", "apple"),
    "F4-0F-24": ("Apple", "apple"),
    "F4-1B-A1": ("Apple", "apple"),
    "F4-31-C3": ("Apple", "apple"),
    "F4-37-B7": ("Apple", "apple"),
    "F4-5C-89": ("Apple", "apple"),
    "F4-F1-5A": ("Apple", "apple"),
    "F4-F9-51": ("Apple", "apple"),
    "F8-1E-DF": ("Apple", "apple"),
    "F8-27-93": ("Apple", "apple"),
    "F8-38-80": ("Apple", "apple"),
    "F8-4D-89": ("Apple", "apple"),
    "F8-62-14": ("Apple", "apple"),
    "F8-95-EA": ("Apple", "apple"),
    "FC-25-3F": ("Apple", "apple"),
    "FC-D8-48": ("Apple", "apple"),
    "FC-E9-98": ("Apple", "apple"),
    "FC-FC-48": ("Apple", "apple"),

    # Samsung
    "00-00-F0": ("Samsung", "samsung"),
    "00-02-78": ("Samsung", "samsung"),
    "00-07-AB": ("Samsung", "samsung"),
    "00-09-18": ("Samsung", "samsung"),
    "00-0D-AE": ("Samsung", "samsung"),
    "00-0D-E5": ("Samsung", "samsung"),
    "00-12-47": ("Samsung", "samsung"),
    "00-12-FB": ("Samsung", "samsung"),
    "00-13-77": ("Samsung", "samsung"),
    "00-15-99": ("Samsung", "samsung"),
    "00-15-B9": ("Samsung", "samsung"),
    "00-16-32": ("Samsung", "samsung"),
    "00-16-6B": ("Samsung", "samsung"),
    "00-16-6C": ("Samsung", "samsung"),
    "00-16-DB": ("Samsung", "samsung"),
    "00-17-C9": ("Samsung", "samsung"),
    "00-17-D5": ("Samsung", "samsung"),
    "00-18-AF": ("Samsung", "samsung"),
    "00-1A-8A": ("Samsung", "samsung"),
    "00-1B-98": ("Samsung", "samsung"),
    "00-1C-43": ("Samsung", "samsung"),
    "00-1D-25": ("Samsung", "samsung"),
    "00-1D-F6": ("Samsung", "samsung"),
    "00-1E-7D": ("Samsung", "samsung"),
    "00-1F-CC": ("Samsung", "samsung"),
    "00-1F-CD": ("Samsung", "samsung"),
    "00-21-19": ("Samsung", "samsung"),
    "00-21-4C": ("Samsung", "samsung"),
    "00-21-D1": ("Samsung", "samsung"),
    "00-21-D2": ("Samsung", "samsung"),
    "00-23-39": ("Samsung", "samsung"),
    "00-23-3A": ("Samsung", "samsung"),
    "00-23-99": ("Samsung", "samsung"),
    "00-23-D6": ("Samsung", "samsung"),
    "00-23-D7": ("Samsung", "samsung"),
    "00-24-54": ("Samsung", "samsung"),
    "00-24-90": ("Samsung", "samsung"),
    "00-24-91": ("Samsung", "samsung"),
    "00-24-E9": ("Samsung", "samsung"),
    "00-25-66": ("Samsung", "samsung"),
    "00-25-67": ("Samsung", "samsung"),
    "00-26-37": ("Samsung", "samsung"),
    "00-26-5D": ("Samsung", "samsung"),
    "00-26-5F": ("Samsung", "samsung"),
    "08-08-C2": ("Samsung", "samsung"),
    "08-D4-2B": ("Samsung", "samsung"),
    "08-EE-8B": ("Samsung", "samsung"),
    "08-FC-88": ("Samsung", "samsung"),
    "0C-14-20": ("Samsung", "samsung"),
    "0C-71-5D": ("Samsung", "samsung"),
    "0C-89-10": ("Samsung", "samsung"),
    "10-1D-C0": ("Samsung", "samsung"),
    "10-30-47": ("Samsung", "samsung"),
    "14-49-E0": ("Samsung", "samsung"),
    "14-89-FD": ("Samsung", "samsung"),
    "18-3A-2D": ("Samsung", "samsung"),
    "18-67-B0": ("Samsung", "samsung"),
    "18-E2-C2": ("Samsung", "samsung"),
    "1C-62-B8": ("Samsung", "samsung"),
    "1C-66-AA": ("Samsung", "samsung"),
    "20-13-E0": ("Samsung", "samsung"),
    "20-55-31": ("Samsung", "samsung"),
    "20-64-32": ("Samsung", "samsung"),
    "20-D3-90": ("Samsung", "samsung"),
    "24-4B-81": ("Samsung", "samsung"),
    "24-C6-96": ("Samsung", "samsung"),
    "28-27-BF": ("Samsung", "samsung"),
    "28-98-7B": ("Samsung", "samsung"),
    "28-BA-B5": ("Samsung", "samsung"),
    "2C-44-01": ("Samsung", "samsung"),
    "2C-AE-2B": ("Samsung", "samsung"),
    "30-19-66": ("Samsung", "samsung"),
    "30-96-FB": ("Samsung", "samsung"),
    "30-CD-A7": ("Samsung", "samsung"),
    "30-D6-C9": ("Samsung", "samsung"),
    "34-14-5F": ("Samsung", "samsung"),
    "34-23-BA": ("Samsung", "samsung"),
    "34-BE-00": ("Samsung", "samsung"),
    "34-C3-AC": ("Samsung", "samsung"),
    "38-0A-94": ("Samsung", "samsung"),
    "38-01-97": ("Samsung", "samsung"),
    "38-16-D1": ("Samsung", "samsung"),
    "38-2D-D1": ("Samsung", "samsung"),
    "38-2D-E8": ("Samsung", "samsung"),
    "38-AA-3C": ("Samsung", "samsung"),
    "3C-5A-37": ("Samsung", "samsung"),
    "3C-8B-FE": ("Samsung", "samsung"),
    "40-0E-85": ("Samsung", "samsung"),
    "44-4E-1A": ("Samsung", "samsung"),
    "44-6D-6C": ("Samsung", "samsung"),
    "44-78-3E": ("Samsung", "samsung"),
    "48-13-7E": ("Samsung", "samsung"),
    "48-44-F7": ("Samsung", "samsung"),
    "4C-3C-16": ("Samsung", "samsung"),
    "4C-BC-A5": ("Samsung", "samsung"),
    "50-01-BB": ("Samsung", "samsung"),
    "50-32-75": ("Samsung", "samsung"),
    "50-85-69": ("Samsung", "samsung"),
    "50-A4-D0": ("Samsung", "samsung"),
    "50-B7-C3": ("Samsung", "samsung"),
    "50-C8-E5": ("Samsung", "samsung"),
    "50-F0-D3": ("Samsung", "samsung"),
    "54-40-AD": ("Samsung", "samsung"),
    "54-88-0E": ("Samsung", "samsung"),
    "54-92-BE": ("Samsung", "samsung"),
    "58-C3-8B": ("Samsung", "samsung"),
    "5C-0A-5B": ("Samsung", "samsung"),
    "5C-3C-27": ("Samsung", "samsung"),
    "5C-E8-EB": ("Samsung", "samsung"),
    "60-6B-BD": ("Samsung", "samsung"),
    "60-8F-5C": ("Samsung", "samsung"),
    "60-A1-0A": ("Samsung", "samsung"),
    "60-AF-6D": ("Samsung", "samsung"),
    "64-77-91": ("Samsung", "samsung"),
    "64-B3-10": ("Samsung", "samsung"),
    "68-48-98": ("Samsung", "samsung"),
    "68-EB-AE": ("Samsung", "samsung"),
    "6C-2F-2C": ("Samsung", "samsung"),
    "6C-F3-73": ("Samsung", "samsung"),
    "70-28-8B": ("Samsung", "samsung"),
    "70-F9-27": ("Samsung", "samsung"),
    "74-45-8A": ("Samsung", "samsung"),
    "74-A7-EA": ("Samsung", "samsung"),
    "78-1F-DB": ("Samsung", "samsung"),
    "78-25-AD": ("Samsung", "samsung"),
    "78-40-E4": ("Samsung", "samsung"),
    "78-47-1D": ("Samsung", "samsung"),
    "78-52-1A": ("Samsung", "samsung"),
    "78-9E-D0": ("Samsung", "samsung"),
    "78-AB-BB": ("Samsung", "samsung"),
    "78-BD-BC": ("Samsung", "samsung"),
    "78-D6-F0": ("Samsung", "samsung"),
    "7C-0B-C6": ("Samsung", "samsung"),
    "7C-11-CB": ("Samsung", "samsung"),
    "7C-1C-4E": ("Samsung", "samsung"),
    "7C-F8-54": ("Samsung", "samsung"),
    "80-18-A7": ("Samsung", "samsung"),
    "80-1F-02": ("Samsung", "samsung"),
    "80-56-F2": ("Samsung", "samsung"),
    "80-65-6D": ("Samsung", "samsung"),
    "84-11-9E": ("Samsung", "samsung"),
    "84-25-DB": ("Samsung", "samsung"),
    "84-2E-27": ("Samsung", "samsung"),
    "84-38-38": ("Samsung", "samsung"),
    "84-55-A5": ("Samsung", "samsung"),
    "84-A4-66": ("Samsung", "samsung"),
    "84-B5-41": ("Samsung", "samsung"),
    "84-C7-EA": ("Samsung", "samsung"),
    "88-32-9B": ("Samsung", "samsung"),
    "88-9B-39": ("Samsung", "samsung"),
    "8C-71-F8": ("Samsung", "samsung"),
    "8C-77-12": ("Samsung", "samsung"),
    "8C-F5-A3": ("Samsung", "samsung"),
    "90-00-DB": ("Samsung", "samsung"),
    "90-18-7C": ("Samsung", "samsung"),
    "90-F1-AA": ("Samsung", "samsung"),
    "94-01-C2": ("Samsung", "samsung"),
    "94-35-0A": ("Samsung", "samsung"),
    "94-51-03": ("Samsung", "samsung"),
    "94-63-D1": ("Samsung", "samsung"),
    "94-B1-0A": ("Samsung", "samsung"),
    "94-D7-71": ("Samsung", "samsung"),
    "98-0C-82": ("Samsung", "samsung"),
    "98-39-8E": ("Samsung", "samsung"),
    "98-52-B1": ("Samsung", "samsung"),
    "9C-02-98": ("Samsung", "samsung"),
    "9C-3A-AF": ("Samsung", "samsung"),
    "9C-E6-E7": ("Samsung", "samsung"),
    "A0-07-98": ("Samsung", "samsung"),
    "A0-0B-BA": ("Samsung", "samsung"),
    "A0-21-95": ("Samsung", "samsung"),
    "A0-82-1F": ("Samsung", "samsung"),
    "A0-CC-2B": ("Samsung", "samsung"),
    "A4-07-B6": ("Samsung", "samsung"),
    "A4-34-D9": ("Samsung", "samsung"),
    "A8-06-00": ("Samsung", "samsung"),
    "A8-F2-74": ("Samsung", "samsung"),
    "AC-36-13": ("Samsung", "samsung"),
    "AC-5A-14": ("Samsung", "samsung"),
    "B0-47-BF": ("Samsung", "samsung"),
    "B0-72-BF": ("Samsung", "samsung"),
    "B0-C5-59": ("Samsung", "samsung"),
    "B0-EC-71": ("Samsung", "samsung"),
    "B4-07-F9": ("Samsung", "samsung"),
    "B4-3A-28": ("Samsung", "samsung"),
    "B4-62-93": ("Samsung", "samsung"),
    "B4-79-A7": ("Samsung", "samsung"),
    "B4-EF-FA": ("Samsung", "samsung"),
    "B8-5E-7B": ("Samsung", "samsung"),
    "B8-BC-1B": ("Samsung", "samsung"),
    "B8-D9-CE": ("Samsung", "samsung"),
    "BC-14-85": ("Samsung", "samsung"),
    "BC-20-A4": ("Samsung", "samsung"),
    "BC-44-86": ("Samsung", "samsung"),
    "BC-47-60": ("Samsung", "samsung"),
    "BC-72-B1": ("Samsung", "samsung"),
    "BC-79-AD": ("Samsung", "samsung"),
    "BC-85-1F": ("Samsung", "samsung"),
    "BC-8C-CD": ("Samsung", "samsung"),
    "BC-B1-F3": ("Samsung", "samsung"),
    "C0-97-27": ("Samsung", "samsung"),
    "C4-42-02": ("Samsung", "samsung"),
    "C4-57-6E": ("Samsung", "samsung"),
    "C4-73-1E": ("Samsung", "samsung"),
    "C8-14-79": ("Samsung", "samsung"),
    "C8-19-F7": ("Samsung", "samsung"),
    "C8-50-E9": ("Samsung", "samsung"),
    "C8-BA-94": ("Samsung", "samsung"),
    "CC-07-AB": ("Samsung", "samsung"),
    "CC-3A-61": ("Samsung", "samsung"),
    "D0-22-BE": ("Samsung", "samsung"),
    "D0-59-E4": ("Samsung", "samsung"),
    "D0-66-7B": ("Samsung", "samsung"),
    "D0-87-E2": ("Samsung", "samsung"),
    "D0-C1-B1": ("Samsung", "samsung"),
    "D0-DF-C7": ("Samsung", "samsung"),
    "D4-87-D8": ("Samsung", "samsung"),
    "D4-88-90": ("Samsung", "samsung"),
    "D8-57-EF": ("Samsung", "samsung"),
    "D8-90-E8": ("Samsung", "samsung"),
    "D8-C4-E9": ("Samsung", "samsung"),
    "DC-66-72": ("Samsung", "samsung"),
    "E0-99-71": ("Samsung", "samsung"),
    "E0-CB-1D": ("Samsung", "samsung"),
    "E0-DB-10": ("Samsung", "samsung"),
    "E4-12-1D": ("Samsung", "samsung"),
    "E4-32-CB": ("Samsung", "samsung"),
    "E4-58-B8": ("Samsung", "samsung"),
    "E4-7C-F9": ("Samsung", "samsung"),
    "E4-92-FB": ("Samsung", "samsung"),
    "E4-E0-C5": ("Samsung", "samsung"),
    "E8-03-9A": ("Samsung", "samsung"),
    "E8-11-32": ("Samsung", "samsung"),
    "E8-50-8B": ("Samsung", "samsung"),
    "EC-1F-72": ("Samsung", "samsung"),
    "EC-9B-F3": ("Samsung", "samsung"),
    "F0-08-F1": ("Samsung", "samsung"),
    "F0-25-B7": ("Samsung", "samsung"),
    "F0-43-47": ("Samsung", "samsung"),
    "F0-5A-09": ("Samsung", "samsung"),
    "F0-6B-CA": ("Samsung", "samsung"),
    "F0-72-8C": ("Samsung", "samsung"),
    "F4-09-D8": ("Samsung", "samsung"),
    "F4-42-8F": ("Samsung", "samsung"),
    "F4-7B-5E": ("Samsung", "samsung"),
    "F4-D9-FB": ("Samsung", "samsung"),
    "F8-04-2E": ("Samsung", "samsung"),
    "F8-77-B8": ("Samsung", "samsung"),
    "FC-19-10": ("Samsung", "samsung"),
    "FC-A1-3E": ("Samsung", "samsung"),

    # Google / Chromecast
    "00-1A-11": ("Google", "google"),
    "1C-F2-9A": ("Google", "google"),
    "30-FD-38": ("Google", "google"),
    "3C-5A-B4": ("Google", "google"),
    "48-D6-D5": ("Google", "google"),
    "54-60-09": ("Google", "google"),
    "58-CB-52": ("Google", "google"),
    "6C-AD-F8": ("Google", "google"),
    "70-F0-87": ("Google", "google"),
    "94-EB-2C": ("Google", "google"),
    "98-D2-93": ("Google", "google"),
    "A4-77-33": ("Google", "google"),
    "D4-F5-47": ("Google", "google"),
    "DC-D2-FC": ("Google", "google"),
    "E4-F0-42": ("Google", "google"),
    "F0-EF-86": ("Google", "google"),
    "F4-F5-D8": ("Google", "google"),
    "F4-F5-E8": ("Google", "google"),
    "F8-0F-F9": ("Google", "google"),
    "FA-8F-CA": ("Google", "google"),
    "54-27-1E": ("Google", "google"),
    "24-E5-0F": ("Google", "google_nest"),

    # Amazon (Echo, Fire TV, Ring)
    "00-BB-3A": ("Amazon", "amazon"),
    "00-FC-8B": ("Amazon", "amazon"),
    "04-E5-98": ("Amazon", "amazon"),
    "0C-47-C9": ("Amazon", "amazon"),
    "10-CE-A9": ("Amazon", "amazon"),
    "14-91-82": ("Amazon", "amazon"),
    "18-74-2E": ("Amazon", "amazon"),
    "18-AF-61": ("Amazon", "amazon"),
    "24-4C-E3": ("Amazon", "amazon"),
    "28-EF-01": ("Amazon", "amazon"),
    "34-D2-70": ("Amazon", "amazon"),
    "38-F7-3D": ("Amazon", "amazon"),
    "40-A2-DB": ("Amazon", "amazon"),
    "40-B4-CD": ("Amazon", "amazon"),
    "44-00-49": ("Amazon", "amazon"),
    "44-65-0D": ("Amazon", "amazon"),
    "4C-EF-C0": ("Amazon", "amazon"),
    "50-DC-E7": ("Amazon", "amazon"),
    "50-F5-DA": ("Amazon", "amazon"),
    "58-38-79": ("Amazon", "amazon"),
    "5C-41-5A": ("Amazon", "amazon"),
    "68-37-E9": ("Amazon", "amazon"),
    "68-54-FD": ("Amazon", "amazon"),
    "68-9C-70": ("Amazon", "amazon"),
    "6C-56-97": ("Amazon", "amazon"),
    "74-75-48": ("Amazon", "amazon"),
    "74-C2-46": ("Amazon", "amazon"),
    "78-E1-03": ("Amazon", "amazon"),
    "84-D6-D0": ("Amazon", "amazon"),
    "8C-49-62": ("Amazon", "amazon"),
    "A0-02-DC": ("Amazon", "amazon"),
    "AC-63-BE": ("Amazon", "amazon"),
    "B0-FC-0D": ("Amazon", "amazon"),
    "B4-7C-9C": ("Amazon", "amazon"),
    "C8-3D-D4": ("Amazon", "amazon"),
    "CC-F7-35": ("Amazon", "amazon"),
    "F0-27-2D": ("Amazon", "amazon"),
    "F0-81-73": ("Amazon", "amazon"),
    "F0-F0-A4": ("Amazon", "amazon"),
    "FC-65-DE": ("Amazon", "amazon"),
    "FC-A1-83": ("Amazon", "amazon"),

    # Roku
    "08-05-81": ("Roku", "roku"),
    "0C-62-A6": ("Roku", "roku"),
    "10-59-32": ("Roku", "roku"),
    "20-EF-BD": ("Roku", "roku"),
    "2C-E4-10": ("Roku", "roku"),
    "84-EA-ED": ("Roku", "roku"),
    "88-DE-A9": ("Roku", "roku"),
    "AC-3A-7A": ("Roku", "roku"),
    "B0-A7-37": ("Roku", "roku"),
    "B8-3E-59": ("Roku", "roku"),
    "C8-3A-6B": ("Roku", "roku"),
    "CC-6D-A0": ("Roku", "roku"),
    "D0-4D-C6": ("Roku", "roku"),
    "D8-31-34": ("Roku", "roku"),
    "DC-3A-5E": ("Roku", "roku"),

    # Sonos
    "00-0E-58": ("Sonos", "sonos"),
    "34-7E-5C": ("Sonos", "sonos"),
    "48-A6-B8": ("Sonos", "sonos"),
    "5C-AA-FD": ("Sonos", "sonos"),
    "78-28-CA": ("Sonos", "sonos"),
    "94-9F-3E": ("Sonos", "sonos"),
    "B8-E9-37": ("Sonos", "sonos"),

    # Ring (Doorbell/Camera)
    "30-45-11": ("Ring", "ring"),
    "40-E3-D6": ("Ring", "ring"),
    "5C-47-5E": ("Ring", "ring"),
    "AC-64-DD": ("Ring", "ring"),
    "D4-B8-FF": ("Ring", "ring"),

    # Nest (Thermostat, Camera)
    "18-B4-30": ("Nest", "nest"),
    "64-16-66": ("Nest", "nest"),

    # Philips Hue
    "00-17-88": ("Philips Hue", "philips_hue"),
    "EC-B5-FA": ("Philips Hue", "philips_hue"),

    # LG (TV, Mobile)
    "00-05-C9": ("LG", "lg"),
    "00-1C-62": ("LG", "lg"),
    "00-1E-75": ("LG", "lg"),
    "00-1F-6B": ("LG", "lg"),
    "00-1F-E2": ("LG", "lg"),
    "00-22-A9": ("LG", "lg"),
    "00-24-83": ("LG", "lg"),
    "00-25-E5": ("LG", "lg"),
    "00-26-E2": ("LG", "lg"),
    "00-AA-70": ("LG", "lg"),
    "00-E0-91": ("LG", "lg"),
    "10-68-3F": ("LG", "lg"),
    "14-C9-13": ("LG", "lg"),
    "20-21-A5": ("LG", "lg"),
    "24-FD-52": ("LG", "lg"),
    "28-C6-3F": ("LG", "lg"),
    "2C-54-CF": ("LG", "lg"),
    "30-8C-FB": ("LG", "lg"),
    "34-4D-F7": ("LG", "lg"),
    "38-8C-50": ("LG", "lg"),
    "3C-BD-D8": ("LG", "lg"),
    "40-B0-FA": ("LG", "lg"),
    "44-07-0B": ("LG", "lg"),
    "50-55-27": ("LG", "lg"),
    "54-A5-1B": ("LG", "lg"),
    "58-A2-B5": ("LG", "lg"),
    "5C-70-A3": ("LG", "lg"),
    "64-99-5D": ("LG", "lg"),
    "68-C4-4D": ("LG", "lg"),
    "6C-D0-32": ("LG", "lg"),
    "74-A7-22": ("LG", "lg"),
    "78-5D-C8": ("LG", "lg"),
    "7C-1C-68": ("LG", "lg"),
    "7C-E5-24": ("LG", "lg"),
    "80-AD-67": ("LG", "lg"),
    "84-2E-14": ("LG", "lg"),
    "88-03-55": ("LG", "lg"),
    "88-07-4B": ("LG", "lg"),
    "8C-3A-E3": ("LG", "lg"),
    "8C-C8-CD": ("LG", "lg"),
    "90-21-06": ("LG", "lg"),
    "98-D6-F7": ("LG", "lg"),
    "A8-16-B2": ("LG", "lg"),
    "A8-23-FE": ("LG", "lg"),
    "AC-0D-1B": ("LG", "lg"),
    "B4-E6-2A": ("LG", "lg"),
    "BC-26-2D": ("LG", "lg"),
    "BC-F5-AC": ("LG", "lg"),
    "C0-A3-9E": ("LG", "lg"),
    "C4-36-6C": ("LG", "lg"),
    "CC-2D-8C": ("LG", "lg"),
    "D0-37-45": ("LG", "lg"),
    "D4-53-83": ("LG", "lg"),
    "DC-0B-1A": ("LG", "lg"),
    "E8-5B-5B": ("LG", "lg"),
    "F0-1C-13": ("LG", "lg"),
    "F8-0C-F3": ("LG", "lg"),
    "F8-95-C7": ("LG", "lg"),
    "F8-D0-AC": ("LG", "lg"),
    "FC-78-AF": ("LG", "lg"),

    # Sony (PlayStation, TV)
    "00-01-4A": ("Sony", "sony"),
    "00-04-1F": ("Sony", "sony"),
    "00-13-A9": ("Sony", "sony"),
    "00-19-63": ("Sony", "sony"),
    "00-1A-80": ("Sony", "sony"),
    "00-1D-0D": ("Sony", "sony"),
    "00-1D-BA": ("Sony", "sony"),
    "00-1E-A4": ("Sony", "sony"),
    "00-1F-E4": ("Sony", "sony"),
    "00-24-BE": ("Sony", "sony"),
    "00-EB-2D": ("Sony", "sony"),
    "04-5D-4B": ("Sony", "sony"),
    "04-76-6E": ("Sony", "sony"),
    "08-A6-BC": ("Sony", "sony"),
    "0C-FE-45": ("Sony", "sony"),
    "10-4F-A8": ("Sony", "sony"),
    "18-00-2D": ("Sony", "sony"),
    "1C-E6-C7": ("Sony", "sony"),
    "28-0D-FC": ("Sony", "sony"),
    "30-17-C8": ("Sony", "sony"),
    "30-EB-25": ("Sony", "sony"),
    "40-C6-8F": ("Sony", "sony"),
    "48-C9-8F": ("Sony", "sony"),
    "54-42-49": ("Sony", "sony"),
    "54-EF-92": ("Sony", "sony"),
    "58-48-22": ("Sony", "sony"),
    "58-E4-76": ("Sony", "sony"),
    "5C-B5-24": ("Sony", "sony"),
    "70-9E-29": ("Sony", "sony"),
    "7C-6B-F7": ("Sony", "sony"),
    "7C-E1-FF": ("Sony", "sony"),
    "84-26-15": ("Sony", "sony"),
    "88-79-7E": ("Sony", "sony"),
    "90-FB-A6": ("Sony", "sony"),
    "9C-D6-43": ("Sony", "sony"),
    "A0-55-1B": ("Sony", "sony"),
    "A0-E4-53": ("Sony", "sony"),
    "AC-60-B6": ("Sony", "sony"),
    "B4-52-7E": ("Sony", "sony"),
    "C4-30-18": ("Sony", "sony"),
    "C8-63-F1": ("Sony", "sony"),
    "D4-63-C6": ("Sony", "sony"),
    "D8-CE-3A": ("Sony", "sony"),
    "E0-E7-51": ("Sony", "sony"),
    "E4-7D-BD": ("Sony", "sony"),
    "F4-B7-E2": ("Sony", "sony"),
    "F8-D0-27": ("Sony", "sony"),
    "FC-0F-E6": ("Sony", "sony"),
    "FC-F1-52": ("Sony", "sony"),

    # Microsoft (Xbox, Surface)
    "00-0D-3A": ("Microsoft", "microsoft"),
    "00-12-5A": ("Microsoft", "microsoft"),
    "00-15-5D": ("Microsoft", "microsoft"),  # Hyper-V
    "00-17-FA": ("Microsoft", "microsoft"),
    "00-1D-D8": ("Microsoft", "microsoft"),
    "00-22-48": ("Microsoft", "microsoft"),
    "00-50-F2": ("Microsoft", "microsoft"),
    "28-18-78": ("Microsoft", "microsoft"),
    "30-59-B7": ("Microsoft", "microsoft"),
    "48-50-73": ("Microsoft", "microsoft"),
    "50-1A-C5": ("Microsoft", "microsoft"),
    "58-82-A8": ("Microsoft", "microsoft"),
    "60-45-BD": ("Microsoft", "microsoft"),
    "7C-1E-52": ("Microsoft", "microsoft"),
    "7C-ED-8D": ("Microsoft", "microsoft"),
    "98-5F-D3": ("Microsoft", "microsoft"),
    "C4-9D-ED": ("Microsoft", "microsoft"),
    "C8-3F-26": ("Microsoft", "microsoft"),

    # Nintendo (Switch, Wii)
    "00-09-BF": ("Nintendo", "nintendo"),
    "00-16-56": ("Nintendo", "nintendo"),
    "00-17-AB": ("Nintendo", "nintendo"),
    "00-19-1D": ("Nintendo", "nintendo"),
    "00-19-FD": ("Nintendo", "nintendo"),
    "00-1A-E9": ("Nintendo", "nintendo"),
    "00-1B-7A": ("Nintendo", "nintendo"),
    "00-1B-EA": ("Nintendo", "nintendo"),
    "00-1C-BE": ("Nintendo", "nintendo"),
    "00-1D-BC": ("Nintendo", "nintendo"),
    "00-1E-35": ("Nintendo", "nintendo"),
    "00-1E-A9": ("Nintendo", "nintendo"),
    "00-1F-32": ("Nintendo", "nintendo"),
    "00-1F-C5": ("Nintendo", "nintendo"),
    "00-21-47": ("Nintendo", "nintendo"),
    "00-21-BD": ("Nintendo", "nintendo"),
    "00-22-4C": ("Nintendo", "nintendo"),
    "00-22-AA": ("Nintendo", "nintendo"),
    "00-22-D7": ("Nintendo", "nintendo"),
    "00-23-31": ("Nintendo", "nintendo"),
    "00-23-CC": ("Nintendo", "nintendo"),
    "00-24-1E": ("Nintendo", "nintendo"),
    "00-24-44": ("Nintendo", "nintendo"),
    "00-24-F3": ("Nintendo", "nintendo"),
    "00-25-A0": ("Nintendo", "nintendo"),
    "00-26-59": ("Nintendo", "nintendo"),
    "0C-FE-45": ("Nintendo", "nintendo"),
    "10-5F-06": ("Nintendo", "nintendo"),
    "14-56-8E": ("Nintendo", "nintendo"),
    "18-2A-7B": ("Nintendo", "nintendo"),
    "2C-10-C1": ("Nintendo", "nintendo"),
    "34-AF-2C": ("Nintendo", "nintendo"),
    "40-D2-8A": ("Nintendo", "nintendo"),
    "40-F4-07": ("Nintendo", "nintendo"),
    "58-2F-40": ("Nintendo", "nintendo"),
    "58-BD-A3": ("Nintendo", "nintendo"),
    "5C-52-1E": ("Nintendo", "nintendo"),
    "64-B5-C6": ("Nintendo", "nintendo"),
    "78-A2-A0": ("Nintendo", "nintendo"),
    "7C-BB-8A": ("Nintendo", "nintendo"),
    "8C-56-C5": ("Nintendo", "nintendo"),
    "98-41-5C": ("Nintendo", "nintendo"),
    "98-B6-E9": ("Nintendo", "nintendo"),
    "9C-E6-35": ("Nintendo", "nintendo"),
    "A4-38-CC": ("Nintendo", "nintendo"),
    "B8-8A-60": ("Nintendo", "nintendo"),
    "CC-9E-00": ("Nintendo", "nintendo"),
    "D8-6B-F7": ("Nintendo", "nintendo"),
    "DC-68-EB": ("Nintendo", "nintendo"),
    "E0-0C-7F": ("Nintendo", "nintendo"),
    "E0-E7-51": ("Nintendo", "nintendo"),
    "E8-4E-CE": ("Nintendo", "nintendo"),
    "E8-96-3A": ("Nintendo", "nintendo"),
    "EC-0E-C4": ("Nintendo", "nintendo"),
    "F8-E7-A5": ("Nintendo", "nintendo"),

    # Synology NAS
    "00-11-32": ("Synology", "synology"),

    # QNAP NAS
    "00-08-9B": ("QNAP", "qnap"),
    "24-5E-BE": ("QNAP", "qnap"),

    # TP-Link
    "00-27-19": ("TP-Link", "tp-link"),
    "14-CC-20": ("TP-Link", "tp-link"),
    "14-CF-92": ("TP-Link", "tp-link"),
    "18-A6-F7": ("TP-Link", "tp-link"),
    "1C-61-B4": ("TP-Link", "tp-link"),
    "30-B4-9E": ("TP-Link", "tp-link"),
    "3C-52-A1": ("TP-Link", "tp-link"),
    "44-D9-E7": ("TP-Link", "tp-link"),
    "50-C7-BF": ("TP-Link", "tp-link"),
    "54-C8-0F": ("TP-Link", "tp-link"),
    "58-11-22": ("TP-Link", "tp-link"),
    "60-32-B1": ("TP-Link", "tp-link"),
    "64-70-02": ("TP-Link", "tp-link"),
    "70-4F-57": ("TP-Link", "tp-link"),
    "78-8C-B5": ("TP-Link", "tp-link"),
    "7C-8B-CA": ("TP-Link", "tp-link"),
    "84-16-F9": ("TP-Link", "tp-link"),
    "88-1D-FC": ("TP-Link", "tp-link"),
    "8C-A6-DF": ("TP-Link", "tp-link"),
    "90-F6-52": ("TP-Link", "tp-link"),
    "94-D9-B3": ("TP-Link", "tp-link"),
    "98-DA-C4": ("TP-Link", "tp-link"),
    "9C-53-22": ("TP-Link", "tp-link"),
    "A4-2B-B0": ("TP-Link", "tp-link"),
    "A8-15-4D": ("TP-Link", "tp-link"),
    "AC-15-A2": ("TP-Link", "tp-link"),
    "B0-95-75": ("TP-Link", "tp-link"),
    "B0-BE-76": ("TP-Link", "tp-link"),
    "C0-06-C3": ("TP-Link", "tp-link"),
    "C0-25-E9": ("TP-Link", "tp-link"),
    "C4-6E-1F": ("TP-Link", "tp-link"),
    "C8-3A-35": ("TP-Link", "tp-link"),
    "CC-32-E5": ("TP-Link", "tp-link"),
    "D4-6E-0E": ("TP-Link", "tp-link"),
    "D8-07-B6": ("TP-Link", "tp-link"),
    "DC-FE-18": ("TP-Link", "tp-link"),
    "E4-D3-32": ("TP-Link", "tp-link"),
    "E8-94-F6": ("TP-Link", "tp-link"),
    "EC-08-6B": ("TP-Link", "tp-link"),
    "F4-EC-38": ("TP-Link", "tp-link"),
    "F8-D1-11": ("TP-Link", "tp-link"),

    # Ubiquiti
    "00-15-6D": ("Ubiquiti", "ubiquiti"),
    "00-27-22": ("Ubiquiti", "ubiquiti"),
    "04-18-D6": ("Ubiquiti", "ubiquiti"),
    "18-E8-29": ("Ubiquiti", "ubiquiti"),
    "24-5A-4C": ("Ubiquiti", "ubiquiti"),
    "44-D9-E7": ("Ubiquiti", "ubiquiti"),
    "68-72-51": ("Ubiquiti", "ubiquiti"),
    "68-D7-9A": ("Ubiquiti", "ubiquiti"),
    "74-83-C2": ("Ubiquiti", "ubiquiti"),
    "74-AC-B9": ("Ubiquiti", "ubiquiti"),
    "78-45-58": ("Ubiquiti", "ubiquiti"),
    "78-8A-20": ("Ubiquiti", "ubiquiti"),
    "80-2A-A8": ("Ubiquiti", "ubiquiti"),
    "9C-05-D6": ("Ubiquiti", "ubiquiti"),
    "AC-8B-A9": ("Ubiquiti", "ubiquiti"),
    "B4-FB-E4": ("Ubiquiti", "ubiquiti"),
    "D0-21-F9": ("Ubiquiti", "ubiquiti"),
    "DC-9F-DB": ("Ubiquiti", "ubiquiti"),
    "E0-63-DA": ("Ubiquiti", "ubiquiti"),
    "F0-9F-C2": ("Ubiquiti", "ubiquiti"),
    "FC-EC-DA": ("Ubiquiti", "ubiquiti"),

    # Netgear
    "00-09-5B": ("Netgear", "netgear"),
    "00-0F-B5": ("Netgear", "netgear"),
    "00-14-6C": ("Netgear", "netgear"),
    "00-18-4D": ("Netgear", "netgear"),
    "00-1B-2F": ("Netgear", "netgear"),
    "00-1E-2A": ("Netgear", "netgear"),
    "00-1F-33": ("Netgear", "netgear"),
    "00-22-3F": ("Netgear", "netgear"),
    "00-24-B2": ("Netgear", "netgear"),
    "00-26-F2": ("Netgear", "netgear"),
    "08-BD-43": ("Netgear", "netgear"),
    "10-0C-6B": ("Netgear", "netgear"),
    "10-0D-7F": ("Netgear", "netgear"),
    "10-DA-43": ("Netgear", "netgear"),
    "20-4E-7F": ("Netgear", "netgear"),
    "28-80-88": ("Netgear", "netgear"),
    "28-C6-8E": ("Netgear", "netgear"),
    "2C-B0-5D": ("Netgear", "netgear"),
    "30-46-9A": ("Netgear", "netgear"),
    "38-94-ED": ("Netgear", "netgear"),
    "44-94-FC": ("Netgear", "netgear"),
    "4C-60-DE": ("Netgear", "netgear"),
    "6C-B0-CE": ("Netgear", "netgear"),
    "78-D2-94": ("Netgear", "netgear"),
    "84-1B-5E": ("Netgear", "netgear"),
    "8C-3B-AD": ("Netgear", "netgear"),
    "9C-3D-CF": ("Netgear", "netgear"),
    "A0-04-60": ("Netgear", "netgear"),
    "A0-21-B7": ("Netgear", "netgear"),
    "A0-40-A0": ("Netgear", "netgear"),
    "A4-2B-8C": ("Netgear", "netgear"),
    "B0-7F-B9": ("Netgear", "netgear"),
    "C0-3F-0E": ("Netgear", "netgear"),
    "C4-04-15": ("Netgear", "netgear"),
    "C8-9E-43": ("Netgear", "netgear"),
    "CC-40-D0": ("Netgear", "netgear"),
    "D8-EB-46": ("Netgear", "netgear"),
    "DC-EF-09": ("Netgear", "netgear"),
    "E0-46-9A": ("Netgear", "netgear"),
    "E0-91-F5": ("Netgear", "netgear"),
    "E4-F4-C6": ("Netgear", "netgear"),
    "E8-FC-AF": ("Netgear", "netgear"),

    # ASUS
    "00-0C-6E": ("ASUS", "asus"),
    "00-0E-A6": ("ASUS", "asus"),
    "00-11-2F": ("ASUS", "asus"),
    "00-11-D8": ("ASUS", "asus"),
    "00-13-D4": ("ASUS", "asus"),
    "00-15-F2": ("ASUS", "asus"),
    "00-17-31": ("ASUS", "asus"),
    "00-18-F3": ("ASUS", "asus"),
    "00-1A-92": ("ASUS", "asus"),
    "00-1B-FC": ("ASUS", "asus"),
    "00-1D-60": ("ASUS", "asus"),
    "00-1E-8C": ("ASUS", "asus"),
    "00-1F-C6": ("ASUS", "asus"),
    "00-22-15": ("ASUS", "asus"),
    "00-23-54": ("ASUS", "asus"),
    "00-24-8C": ("ASUS", "asus"),
    "00-25-22": ("ASUS", "asus"),
    "00-26-18": ("ASUS", "asus"),
    "08-60-6E": ("ASUS", "asus"),
    "0C-9D-92": ("ASUS", "asus"),
    "10-7B-44": ("ASUS", "asus"),
    "10-BF-48": ("ASUS", "asus"),
    "14-DA-E9": ("ASUS", "asus"),
    "1C-87-2C": ("ASUS", "asus"),
    "1C-B7-2C": ("ASUS", "asus"),
    "20-CF-30": ("ASUS", "asus"),
    "2C-4D-54": ("ASUS", "asus"),
    "2C-56-DC": ("ASUS", "asus"),
    "30-5A-3A": ("ASUS", "asus"),
    "30-85-A9": ("ASUS", "asus"),
    "34-97-F6": ("ASUS", "asus"),
    "38-2C-4A": ("ASUS", "asus"),
    "38-D5-47": ("ASUS", "asus"),
    "3C-97-0E": ("ASUS", "asus"),
    "40-16-7E": ("ASUS", "asus"),
    "48-5B-39": ("ASUS", "asus"),
    "4C-ED-FB": ("ASUS", "asus"),
    "50-46-5D": ("ASUS", "asus"),
    "54-04-A6": ("ASUS", "asus"),
    "60-45-CB": ("ASUS", "asus"),
    "6C-4B-90": ("ASUS", "asus"),
    "74-D0-2B": ("ASUS", "asus"),
    "74-D4-35": ("ASUS", "asus"),
    "78-24-AF": ("ASUS", "asus"),
    "88-D7-F6": ("ASUS", "asus"),
    "90-E6-BA": ("ASUS", "asus"),
    "AC-22-0B": ("ASUS", "asus"),
    "AC-9E-17": ("ASUS", "asus"),
    "B0-6E-BF": ("ASUS", "asus"),
    "BC-AE-C5": ("ASUS", "asus"),
    "BC-EE-7B": ("ASUS", "asus"),
    "C8-60-00": ("ASUS", "asus"),
    "D8-50-E6": ("ASUS", "asus"),
    "E0-3F-49": ("ASUS", "asus"),
    "E0-CB-4E": ("ASUS", "asus"),
    "F0-79-59": ("ASUS", "asus"),
    "F4-6D-04": ("ASUS", "asus"),
    "F8-32-E4": ("ASUS", "asus"),

    # Dell
    "00-06-5B": ("Dell", "dell"),
    "00-08-74": ("Dell", "dell"),
    "00-0B-DB": ("Dell", "dell"),
    "00-0D-56": ("Dell", "dell"),
    "00-0F-1F": ("Dell", "dell"),
    "00-11-43": ("Dell", "dell"),
    "00-12-3F": ("Dell", "dell"),
    "00-13-72": ("Dell", "dell"),
    "00-14-22": ("Dell", "dell"),
    "00-15-C5": ("Dell", "dell"),
    "00-16-F0": ("Dell", "dell"),
    "00-18-8B": ("Dell", "dell"),
    "00-19-B9": ("Dell", "dell"),
    "00-1A-A0": ("Dell", "dell"),
    "00-1C-23": ("Dell", "dell"),
    "00-1D-09": ("Dell", "dell"),
    "00-1E-4F": ("Dell", "dell"),
    "00-1E-C9": ("Dell", "dell"),
    "00-21-70": ("Dell", "dell"),
    "00-21-9B": ("Dell", "dell"),
    "00-22-19": ("Dell", "dell"),
    "00-23-AE": ("Dell", "dell"),
    "00-24-E8": ("Dell", "dell"),
    "00-25-64": ("Dell", "dell"),
    "00-26-B9": ("Dell", "dell"),
    "14-18-77": ("Dell", "dell"),
    "14-B3-1F": ("Dell", "dell"),
    "14-FE-B5": ("Dell", "dell"),
    "18-03-73": ("Dell", "dell"),
    "18-66-DA": ("Dell", "dell"),
    "18-A9-9B": ("Dell", "dell"),
    "18-DB-F2": ("Dell", "dell"),
    "1C-40-24": ("Dell", "dell"),
    "20-47-47": ("Dell", "dell"),
    "24-6E-96": ("Dell", "dell"),
    "24-B6-FD": ("Dell", "dell"),
    "28-C8-25": ("Dell", "dell"),
    "28-F1-0E": ("Dell", "dell"),
    "34-17-EB": ("Dell", "dell"),
    "34-E6-D7": ("Dell", "dell"),
    "44-A8-42": ("Dell", "dell"),
    "48-4D-7E": ("Dell", "dell"),
    "4C-76-25": ("Dell", "dell"),
    "50-9A-4C": ("Dell", "dell"),
    "54-9F-35": ("Dell", "dell"),
    "54-B2-03": ("Dell", "dell"),
    "54-BF-64": ("Dell", "dell"),
    "5C-26-0A": ("Dell", "dell"),
    "5C-F9-DD": ("Dell", "dell"),
    "64-00-6A": ("Dell", "dell"),
    "74-86-7A": ("Dell", "dell"),
    "74-E6-E2": ("Dell", "dell"),
    "78-2B-CB": ("Dell", "dell"),
    "78-45-C4": ("Dell", "dell"),
    "80-18-44": ("Dell", "dell"),
    "84-2B-2B": ("Dell", "dell"),
    "84-7B-EB": ("Dell", "dell"),
    "84-8F-69": ("Dell", "dell"),
    "8C-EC-4B": ("Dell", "dell"),
    "90-B1-1C": ("Dell", "dell"),
    "98-90-96": ("Dell", "dell"),
    "A4-1F-72": ("Dell", "dell"),
    "A4-BA-DB": ("Dell", "dell"),
    "B0-83-FE": ("Dell", "dell"),
    "B4-E1-0F": ("Dell", "dell"),
    "B8-2A-72": ("Dell", "dell"),
    "B8-AC-6F": ("Dell", "dell"),
    "B8-CA-3A": ("Dell", "dell"),
    "BC-30-5B": ("Dell", "dell"),
    "C8-1F-66": ("Dell", "dell"),
    "D0-67-E5": ("Dell", "dell"),
    "D4-81-D7": ("Dell", "dell"),
    "D4-BE-D9": ("Dell", "dell"),
    "E0-DB-55": ("Dell", "dell"),
    "EC-F4-BB": ("Dell", "dell"),
    "F0-1F-AF": ("Dell", "dell"),
    "F4-8E-38": ("Dell", "dell"),
    "F8-B1-56": ("Dell", "dell"),
    "F8-BC-12": ("Dell", "dell"),
    "F8-CA-B8": ("Dell", "dell"),
    "F8-DB-88": ("Dell", "dell"),

    # HP
    "00-01-E6": ("HP", "hp"),
    "00-02-A5": ("HP", "hp"),
    "00-04-EA": ("HP", "hp"),
    "00-08-02": ("HP", "hp"),
    "00-08-83": ("HP", "hp"),
    "00-0A-57": ("HP", "hp"),
    "00-0B-CD": ("HP", "hp"),
    "00-0D-9D": ("HP", "hp"),
    "00-0E-7F": ("HP", "hp"),
    "00-0F-20": ("HP", "hp"),
    "00-10-83": ("HP", "hp"),
    "00-11-0A": ("HP", "hp"),
    "00-11-85": ("HP", "hp"),
    "00-12-79": ("HP", "hp"),
    "00-13-21": ("HP", "hp"),
    "00-14-38": ("HP", "hp"),
    "00-14-C2": ("HP", "hp"),
    "00-15-60": ("HP", "hp"),
    "00-16-35": ("HP", "hp"),
    "00-17-08": ("HP", "hp"),
    "00-17-A4": ("HP", "hp"),
    "00-18-71": ("HP", "hp"),
    "00-18-FE": ("HP", "hp"),
    "00-19-BB": ("HP", "hp"),
    "00-1A-4B": ("HP", "hp"),
    "00-1B-78": ("HP", "hp"),
    "00-1C-2E": ("HP", "hp"),
    "00-1C-C4": ("HP", "hp"),
    "00-1D-31": ("HP", "hp"),
    "00-1D-B3": ("HP", "hp"),
    "00-1E-0B": ("HP", "hp"),
    "00-1E-68": ("HP", "hp"),
    "00-1F-29": ("HP", "hp"),
    "00-1F-FE": ("HP", "hp"),
    "00-21-5A": ("HP", "hp"),
    "00-21-F6": ("HP", "hp"),
    "00-22-64": ("HP", "hp"),
    "00-23-7D": ("HP", "hp"),
    "00-24-81": ("HP", "hp"),
    "00-25-B3": ("HP", "hp"),
    "00-26-55": ("HP", "hp"),
    "00-26-F1": ("HP", "hp"),
    "08-2E-5F": ("HP", "hp"),
    "0C-C4-7A": ("HP", "hp"),
    "10-1F-74": ("HP", "hp"),
    "10-60-4B": ("HP", "hp"),
    "10-E7-C6": ("HP", "hp"),
    "14-02-EC": ("HP", "hp"),
    "14-58-D0": ("HP", "hp"),
    "18-A9-05": ("HP", "hp"),
    "1C-98-EC": ("HP", "hp"),
    "1C-C1-DE": ("HP", "hp"),
    "24-BE-05": ("HP", "hp"),
    "28-80-23": ("HP", "hp"),
    "28-92-4A": ("HP", "hp"),
    "2C-27-D7": ("HP", "hp"),
    "2C-41-38": ("HP", "hp"),
    "2C-44-FD": ("HP", "hp"),
    "2C-59-E5": ("HP", "hp"),
    "2C-76-8A": ("HP", "hp"),
    "30-8D-99": ("HP", "hp"),
    "30-E1-71": ("HP", "hp"),
    "34-64-A9": ("HP", "hp"),
    "34-FC-B9": ("HP", "hp"),
    "38-63-BB": ("HP", "hp"),
    "38-EA-A7": ("HP", "hp"),
    "3C-4A-92": ("HP", "hp"),
    "3C-52-82": ("HP", "hp"),
    "3C-61-05": ("HP", "hp"),
    "3C-A8-2A": ("HP", "hp"),
    "3C-D9-2B": ("HP", "hp"),
    "40-A8-F0": ("HP", "hp"),
    "44-1E-A1": ("HP", "hp"),
    "44-31-92": ("HP", "hp"),
    "48-0F-CF": ("HP", "hp"),
    "48-BA-4E": ("HP", "hp"),
    "4C-39-09": ("HP", "hp"),
    "50-65-F3": ("HP", "hp"),
    "50-EB-71": ("HP", "hp"),
    "54-EE-75": ("HP", "hp"),
    "58-20-B1": ("HP", "hp"),
    "5C-8A-38": ("HP", "hp"),
    "5C-B9-01": ("HP", "hp"),
    "60-EB-69": ("HP", "hp"),
    "64-31-50": ("HP", "hp"),
    "64-51-06": ("HP", "hp"),
    "68-B5-99": ("HP", "hp"),
    "6C-3B-E5": ("HP", "hp"),
    "6C-C2-17": ("HP", "hp"),
    "70-10-6F": ("HP", "hp"),
    "74-46-A0": ("HP", "hp"),
    "78-48-59": ("HP", "hp"),
    "78-AC-C0": ("HP", "hp"),
    "78-E3-B5": ("HP", "hp"),
    "78-E7-D1": ("HP", "hp"),
    "80-C1-6E": ("HP", "hp"),
    "84-34-97": ("HP", "hp"),
    "84-A9-3E": ("HP", "hp"),
    "88-51-FB": ("HP", "hp"),
    "8C-DC-D4": ("HP", "hp"),
    "94-0C-6D": ("HP", "hp"),
    "94-57-A5": ("HP", "hp"),
    "98-4B-E1": ("HP", "hp"),
    "98-E7-F4": ("HP", "hp"),
    "9C-8E-99": ("HP", "hp"),
    "9C-B6-54": ("HP", "hp"),
    "9C-D2-1E": ("HP", "hp"),
    "A0-1D-48": ("HP", "hp"),
    "A0-2B-B8": ("HP", "hp"),
    "A0-48-1C": ("HP", "hp"),
    "A0-8C-FD": ("HP", "hp"),
    "A0-D3-C1": ("HP", "hp"),
    "A4-5D-36": ("HP", "hp"),
    "AC-16-2D": ("HP", "hp"),
    "B0-5A-DA": ("HP", "hp"),
    "B4-99-BA": ("HP", "hp"),
    "B4-B5-2F": ("HP", "hp"),
    "B8-AF-67": ("HP", "hp"),
    "BC-EA-FA": ("HP", "hp"),
    "C0-3F-D5": ("HP", "hp"),
    "C4-34-6B": ("HP", "hp"),
    "C8-CB-B8": ("HP", "hp"),
    "C8-D3-FF": ("HP", "hp"),
    "CC-3D-82": ("HP", "hp"),
    "D0-7E-28": ("HP", "hp"),
    "D4-85-64": ("HP", "hp"),
    "D4-C9-EF": ("HP", "hp"),
    "D8-9E-F3": ("HP", "hp"),
    "D8-D3-85": ("HP", "hp"),
    "DC-4A-3E": ("HP", "hp"),
    "E4-11-5B": ("HP", "hp"),
    "E8-39-35": ("HP", "hp"),
    "E8-F7-24": ("HP", "hp"),
    "EC-8E-B5": ("HP", "hp"),
    "EC-9A-74": ("HP", "hp"),
    "EC-B1-D7": ("HP", "hp"),
    "F0-62-81": ("HP", "hp"),
    "F0-92-1C": ("HP", "hp"),
    "F4-03-21": ("HP", "hp"),
    "F4-39-09": ("HP", "hp"),
    "F4-CE-46": ("HP", "hp"),
    "FC-15-B4": ("HP", "hp"),
    "FC-3F-DB": ("HP", "hp"),

    # Intel
    "00-02-B3": ("Intel", "intel"),
    "00-03-47": ("Intel", "intel"),
    "00-04-23": ("Intel", "intel"),
    "00-07-E9": ("Intel", "intel"),
    "00-0C-F1": ("Intel", "intel"),
    "00-0E-0C": ("Intel", "intel"),
    "00-0E-35": ("Intel", "intel"),
    "00-11-11": ("Intel", "intel"),
    "00-12-F0": ("Intel", "intel"),
    "00-13-02": ("Intel", "intel"),
    "00-13-20": ("Intel", "intel"),
    "00-13-CE": ("Intel", "intel"),
    "00-13-E8": ("Intel", "intel"),
    "00-15-00": ("Intel", "intel"),
    "00-15-17": ("Intel", "intel"),
    "00-16-6F": ("Intel", "intel"),
    "00-16-76": ("Intel", "intel"),
    "00-16-EA": ("Intel", "intel"),
    "00-16-EB": ("Intel", "intel"),
    "00-18-DE": ("Intel", "intel"),
    "00-19-D1": ("Intel", "intel"),
    "00-19-D2": ("Intel", "intel"),
    "00-1B-21": ("Intel", "intel"),
    "00-1B-77": ("Intel", "intel"),
    "00-1C-BF": ("Intel", "intel"),
    "00-1C-C0": ("Intel", "intel"),
    "00-1D-E0": ("Intel", "intel"),
    "00-1D-E1": ("Intel", "intel"),
    "00-1E-64": ("Intel", "intel"),
    "00-1E-65": ("Intel", "intel"),
    "00-1E-67": ("Intel", "intel"),
    "00-1F-3B": ("Intel", "intel"),
    "00-1F-3C": ("Intel", "intel"),
    "00-20-78": ("Intel", "intel"),
    "00-21-5C": ("Intel", "intel"),
    "00-21-5D": ("Intel", "intel"),
    "00-21-6A": ("Intel", "intel"),
    "00-21-6B": ("Intel", "intel"),
    "00-22-FA": ("Intel", "intel"),
    "00-22-FB": ("Intel", "intel"),
    "00-23-14": ("Intel", "intel"),
    "00-23-15": ("Intel", "intel"),
    "00-24-D6": ("Intel", "intel"),
    "00-24-D7": ("Intel", "intel"),
    "00-26-C6": ("Intel", "intel"),
    "00-26-C7": ("Intel", "intel"),
    "00-27-10": ("Intel", "intel"),
    "00-90-27": ("Intel", "intel"),
    "00-A0-C9": ("Intel", "intel"),
    "00-AA-00": ("Intel", "intel"),
    "00-AA-01": ("Intel", "intel"),
    "00-AA-02": ("Intel", "intel"),
    "00-D0-B7": ("Intel", "intel"),
    "08-11-96": ("Intel", "intel"),
    "08-D4-0C": ("Intel", "intel"),
    "10-0B-A9": ("Intel", "intel"),
    "10-4A-7D": ("Intel", "intel"),
    "10-63-C8": ("Intel", "intel"),
    "18-1E-B0": ("Intel", "intel"),
    "18-3D-A2": ("Intel", "intel"),
    "18-FF-0F": ("Intel", "intel"),
    "1C-1B-0D": ("Intel", "intel"),
    "20-16-B9": ("Intel", "intel"),
    "24-77-03": ("Intel", "intel"),
    "28-B2-BD": ("Intel", "intel"),
    "28-E3-47": ("Intel", "intel"),
    "30-24-32": ("Intel", "intel"),
    "34-02-86": ("Intel", "intel"),
    "34-13-E8": ("Intel", "intel"),
    "34-E6-AD": ("Intel", "intel"),
    "3C-A9-F4": ("Intel", "intel"),
    "3C-F8-62": ("Intel", "intel"),
    "40-25-C2": ("Intel", "intel"),
    "40-A3-CC": ("Intel", "intel"),
    "44-85-00": ("Intel", "intel"),
    "48-45-20": ("Intel", "intel"),
    "48-51-B7": ("Intel", "intel"),
    "48-E9-F1": ("Intel", "intel"),
    "4C-34-88": ("Intel", "intel"),
    "4C-79-BA": ("Intel", "intel"),
    "4C-80-93": ("Intel", "intel"),
    "50-2D-A2": ("Intel", "intel"),
    "50-E5-49": ("Intel", "intel"),
    "54-8C-A0": ("Intel", "intel"),
    "58-6D-8F": ("Intel", "intel"),
    "58-91-CF": ("Intel", "intel"),
    "58-A8-39": ("Intel", "intel"),
    "5C-51-4F": ("Intel", "intel"),
    "5C-87-9C": ("Intel", "intel"),
    "5C-C5-D4": ("Intel", "intel"),
    "5C-E0-C5": ("Intel", "intel"),
    "60-2A-D0": ("Intel", "intel"),
    "60-36-DD": ("Intel", "intel"),
    "60-57-18": ("Intel", "intel"),
    "60-6C-66": ("Intel", "intel"),
    "60-D8-19": ("Intel", "intel"),
    "64-80-99": ("Intel", "intel"),
    "64-D4-DA": ("Intel", "intel"),
    "68-05-CA": ("Intel", "intel"),
    "68-17-29": ("Intel", "intel"),
    "68-5D-43": ("Intel", "intel"),
    "6C-29-95": ("Intel", "intel"),
    "6C-88-14": ("Intel", "intel"),
    "70-1C-E7": ("Intel", "intel"),
    "70-5A-0F": ("Intel", "intel"),
    "74-C6-3B": ("Intel", "intel"),
    "74-E5-0B": ("Intel", "intel"),
    "78-0C-B8": ("Intel", "intel"),
    "78-2B-CB": ("Intel", "intel"),
    "78-92-9C": ("Intel", "intel"),
    "78-FF-57": ("Intel", "intel"),
    "7C-7A-91": ("Intel", "intel"),
    "7C-CC-B8": ("Intel", "intel"),
    "7C-D1-C3": ("Intel", "intel"),
    "80-00-0B": ("Intel", "intel"),
    "80-19-34": ("Intel", "intel"),
    "80-86-F2": ("Intel", "intel"),
    "80-9B-20": ("Intel", "intel"),
    "84-3A-4B": ("Intel", "intel"),
    "84-A6-C8": ("Intel", "intel"),
    "84-EF-18": ("Intel", "intel"),
    "88-53-2E": ("Intel", "intel"),
    "88-78-73": ("Intel", "intel"),
    "88-B1-11": ("Intel", "intel"),
    "8C-A9-82": ("Intel", "intel"),
    "8C-B8-4A": ("Intel", "intel"),
    "90-2B-34": ("Intel", "intel"),
    "90-48-9A": ("Intel", "intel"),
    "90-E2-BA": ("Intel", "intel"),
    "94-65-9C": ("Intel", "intel"),
    "94-E9-79": ("Intel", "intel"),
    "98-4F-EE": ("Intel", "intel"),
    "98-5F-D3": ("Intel", "intel"),
    "9C-4E-36": ("Intel", "intel"),
    "9C-DA-3E": ("Intel", "intel"),
    "A0-36-9F": ("Intel", "intel"),
    "A0-88-69": ("Intel", "intel"),
    "A0-A4-C5": ("Intel", "intel"),
    "A0-C5-89": ("Intel", "intel"),
    "A4-02-B9": ("Intel", "intel"),
    "A4-34-D9": ("Intel", "intel"),
    "A4-4E-31": ("Intel", "intel"),
    "A4-C4-94": ("Intel", "intel"),
    "A8-6D-AA": ("Intel", "intel"),
    "A8-7E-E0": ("Intel", "intel"),
    "AC-2B-6E": ("Intel", "intel"),
    "AC-7B-A1": ("Intel", "intel"),
    "AC-FD-CE": ("Intel", "intel"),
    "B4-0E-DE": ("Intel", "intel"),
    "B4-6B-FC": ("Intel", "intel"),
    "B4-96-91": ("Intel", "intel"),
    "B4-D5-BD": ("Intel", "intel"),
    "B8-08-CF": ("Intel", "intel"),
    "B8-8A-60": ("Intel", "intel"),
    "BC-77-37": ("Intel", "intel"),
    "BC-83-85": ("Intel", "intel"),
    "BC-A8-A6": ("Intel", "intel"),
    "C0-B6-58": ("Intel", "intel"),
    "C0-BF-BE": ("Intel", "intel"),
    "C4-E9-84": ("Intel", "intel"),
    "C8-0A-A9": ("Intel", "intel"),
    "C8-5B-76": ("Intel", "intel"),
    "C8-F7-33": ("Intel", "intel"),
    "CC-2F-71": ("Intel", "intel"),
    "CC-3D-82": ("Intel", "intel"),
    "D0-7E-35": ("Intel", "intel"),
    "D4-3B-04": ("Intel", "intel"),
    "D4-6D-6D": ("Intel", "intel"),
    "D4-AE-52": ("Intel", "intel"),
    "D4-BE-D9": ("Intel", "intel"),
    "D4-C9-EF": ("Intel", "intel"),
    "D8-50-E6": ("Intel", "intel"),
    "D8-5D-E2": ("Intel", "intel"),
    "D8-9E-F3": ("Intel", "intel"),
    "DC-0E-A1": ("Intel", "intel"),
    "DC-1B-A1": ("Intel", "intel"),
    "DC-53-60": ("Intel", "intel"),
    "DC-71-96": ("Intel", "intel"),
    "E0-94-67": ("Intel", "intel"),
    "E0-9D-31": ("Intel", "intel"),
    "E0-D4-E8": ("Intel", "intel"),
    "E4-B3-18": ("Intel", "intel"),
    "E4-D5-3D": ("Intel", "intel"),
    "E8-2A-EA": ("Intel", "intel"),
    "E8-40-F2": ("Intel", "intel"),
    "E8-6A-64": ("Intel", "intel"),
    "E8-B1-FC": ("Intel", "intel"),
    "EC-0E-C4": ("Intel", "intel"),
    "F0-03-8C": ("Intel", "intel"),
    "F0-1F-AF": ("Intel", "intel"),
    "F0-77-C3": ("Intel", "intel"),
    "F0-D5-BF": ("Intel", "intel"),
    "F4-06-69": ("Intel", "intel"),
    "F4-8C-50": ("Intel", "intel"),
    "F4-B7-E2": ("Intel", "intel"),
    "F8-0F-41": ("Intel", "intel"),
    "F8-16-54": ("Intel", "intel"),
    "F8-34-41": ("Intel", "intel"),
    "F8-63-3F": ("Intel", "intel"),
    "F8-94-C2": ("Intel", "intel"),
    "FC-F8-AE": ("Intel", "intel"),

    # VMware
    "00-0C-29": ("VMware", "vmware"),
    "00-50-56": ("VMware", "vmware"),
    "00-05-69": ("VMware", "vmware"),

    # Raspberry Pi
    "28-CD-C1": ("Raspberry Pi", "raspberry_pi"),
    "B8-27-EB": ("Raspberry Pi", "raspberry_pi"),
    "D8-3A-DD": ("Raspberry Pi", "raspberry_pi"),
    "DC-A6-32": ("Raspberry Pi", "raspberry_pi"),
    "E4-5F-01": ("Raspberry Pi", "raspberry_pi"),

    # Xiaomi
    "00-9E-C8": ("Xiaomi", "xiaomi"),
    "0C-1D-AF": ("Xiaomi", "xiaomi"),
    "10-2A-B3": ("Xiaomi", "xiaomi"),
    "14-78-07": ("Xiaomi", "xiaomi"),
    "18-59-36": ("Xiaomi", "xiaomi"),
    "20-34-FB": ("Xiaomi", "xiaomi"),
    "28-6C-07": ("Xiaomi", "xiaomi"),
    "34-80-B3": ("Xiaomi", "xiaomi"),
    "38-A4-ED": ("Xiaomi", "xiaomi"),
    "3C-BD-3E": ("Xiaomi", "xiaomi"),
    "44-23-7C": ("Xiaomi", "xiaomi"),
    "50-64-2B": ("Xiaomi", "xiaomi"),
    "58-44-98": ("Xiaomi", "xiaomi"),
    "64-09-80": ("Xiaomi", "xiaomi"),
    "64-B4-73": ("Xiaomi", "xiaomi"),
    "68-DF-DD": ("Xiaomi", "xiaomi"),
    "74-23-44": ("Xiaomi", "xiaomi"),
    "78-02-F8": ("Xiaomi", "xiaomi"),
    "78-11-DC": ("Xiaomi", "xiaomi"),
    "7C-1D-D9": ("Xiaomi", "xiaomi"),
    "84-F3-EB": ("Xiaomi", "xiaomi"),
    "8C-DE-F9": ("Xiaomi", "xiaomi"),
    "9C-99-A0": ("Xiaomi", "xiaomi"),
    "A4-D5-78": ("Xiaomi", "xiaomi"),
    "AC-C1-EE": ("Xiaomi", "xiaomi"),
    "B0-E2-35": ("Xiaomi", "xiaomi"),
    "C4-0B-CB": ("Xiaomi", "xiaomi"),
    "C8-47-8C": ("Xiaomi", "xiaomi"),
    "D4-97-0B": ("Xiaomi", "xiaomi"),
    "E8-AB-FA": ("Xiaomi", "xiaomi"),
    "F0-B4-29": ("Xiaomi", "xiaomi"),
    "F4-F5-DB": ("Xiaomi", "xiaomi"),
    "F8-A4-5F": ("Xiaomi", "xiaomi"),
    "FC-64-BA": ("Xiaomi", "xiaomi"),

    # Wyze camera
    "2C-AA-8E": ("Wyze", "wyze"),
    "7C-78-B2": ("Wyze", "wyze"),
    "D0-3F-27": ("Wyze", "wyze"),

    # Hikvision camera
    "18-68-CB": ("Hikvision", "hikvision"),
    "28-57-BE": ("Hikvision", "hikvision"),
    "44-19-B6": ("Hikvision", "hikvision"),
    "54-C4-15": ("Hikvision", "hikvision"),
    "64-21-84": ("Hikvision", "hikvision"),
    "8C-E7-48": ("Hikvision", "hikvision"),
    "BC-AD-28": ("Hikvision", "hikvision"),
    "C0-56-E3": ("Hikvision", "hikvision"),

    # Eufy camera
    "70-B5-E8": ("Eufy", "eufy"),
    "FC-D4-36": ("Eufy", "eufy"),

    # Dahua camera
    "3C-EF-8C": ("Dahua", "dahua"),
    "D4-43-0E": ("Dahua", "dahua"),
    "E0-50-8B": ("Dahua", "dahua"),

    # Lenovo
    "00-06-1B": ("Lenovo", "lenovo"),
    "00-09-2D": ("Lenovo", "lenovo"),
    "00-0A-E4": ("Lenovo", "lenovo"),
    "00-12-CF": ("Lenovo", "lenovo"),
    "00-16-41": ("Lenovo", "lenovo"),
    "00-1A-6B": ("Lenovo", "lenovo"),
    "00-1E-4C": ("Lenovo", "lenovo"),
    "00-21-CC": ("Lenovo", "lenovo"),
    "00-22-20": ("Lenovo", "lenovo"),
    "00-23-7E": ("Lenovo", "lenovo"),
    "00-24-7E": ("Lenovo", "lenovo"),
    "00-25-D3": ("Lenovo", "lenovo"),
    "00-26-6C": ("Lenovo", "lenovo"),
    "08-D4-0C": ("Lenovo", "lenovo"),
    "10-78-D2": ("Lenovo", "lenovo"),
    "14-1F-BA": ("Lenovo", "lenovo"),
    "18-CC-18": ("Lenovo", "lenovo"),
    "18-DB-F2": ("Lenovo", "lenovo"),
    "1C-1B-B5": ("Lenovo", "lenovo"),
    "20-16-42": ("Lenovo", "lenovo"),
    "20-47-47": ("Lenovo", "lenovo"),
    "24-6E-96": ("Lenovo", "lenovo"),
    "28-D2-44": ("Lenovo", "lenovo"),
    "34-02-86": ("Lenovo", "lenovo"),
    "44-39-C4": ("Lenovo", "lenovo"),
    "50-9A-4C": ("Lenovo", "lenovo"),
    "54-EE-75": ("Lenovo", "lenovo"),
    "58-03-FB": ("Lenovo", "lenovo"),
    "60-57-18": ("Lenovo", "lenovo"),
    "70-5A-0F": ("Lenovo", "lenovo"),
    "7C-21-4A": ("Lenovo", "lenovo"),
    "80-CF-41": ("Lenovo", "lenovo"),
    "98-FA-9B": ("Lenovo", "lenovo"),
    "A4-34-D9": ("Lenovo", "lenovo"),
    "B8-2A-72": ("Lenovo", "lenovo"),
    "C8-0A-A9": ("Lenovo", "lenovo"),
    "D0-57-7B": ("Lenovo", "lenovo"),
    "E4-54-E8": ("Lenovo", "lenovo"),
    "E8-2A-EA": ("Lenovo", "lenovo"),
    "F0-03-8C": ("Lenovo", "lenovo"),
    "F4-8E-38": ("Lenovo", "lenovo"),
    "FC-F8-AE": ("Lenovo", "lenovo"),

    # Cisco
    "00-00-0C": ("Cisco", "cisco"),
    "00-01-42": ("Cisco", "cisco"),
    "00-01-43": ("Cisco", "cisco"),
    "00-01-63": ("Cisco", "cisco"),
    "00-01-64": ("Cisco", "cisco"),
    "00-01-96": ("Cisco", "cisco"),
    "00-01-97": ("Cisco", "cisco"),
    "00-01-C7": ("Cisco", "cisco"),
    "00-01-C9": ("Cisco", "cisco"),
    "00-02-3D": ("Cisco", "cisco"),
    "00-02-4A": ("Cisco", "cisco"),
    "00-02-4B": ("Cisco", "cisco"),
    "00-02-7D": ("Cisco", "cisco"),
    "00-02-7E": ("Cisco", "cisco"),
    "00-02-B9": ("Cisco", "cisco"),
    "00-02-BA": ("Cisco", "cisco"),
    "00-02-FC": ("Cisco", "cisco"),
    "00-02-FD": ("Cisco", "cisco"),
    "00-03-31": ("Cisco", "cisco"),
    "00-03-32": ("Cisco", "cisco"),
    "00-03-6B": ("Cisco", "cisco"),
    "00-03-6C": ("Cisco", "cisco"),
    "00-03-9F": ("Cisco", "cisco"),
    "00-03-A0": ("Cisco", "cisco"),
    "00-03-E3": ("Cisco", "cisco"),
    "00-03-E4": ("Cisco", "cisco"),
    "00-03-FD": ("Cisco", "cisco"),
    "00-03-FE": ("Cisco", "cisco"),
    "00-04-27": ("Cisco", "cisco"),
    "00-04-28": ("Cisco", "cisco"),
    "00-04-4D": ("Cisco", "cisco"),
    "00-04-4E": ("Cisco", "cisco"),
    "00-04-6D": ("Cisco", "cisco"),
    "00-04-6E": ("Cisco", "cisco"),
    "00-04-9A": ("Cisco", "cisco"),
    "00-04-9B": ("Cisco", "cisco"),
    "00-04-C0": ("Cisco", "cisco"),
    "00-04-C1": ("Cisco", "cisco"),
    "00-04-DD": ("Cisco", "cisco"),
    "00-04-DE": ("Cisco", "cisco"),
    "00-05-00": ("Cisco", "cisco"),
    "00-05-01": ("Cisco", "cisco"),
    "00-05-31": ("Cisco", "cisco"),
    "00-05-32": ("Cisco", "cisco"),
    "00-05-5E": ("Cisco", "cisco"),
    "00-05-5F": ("Cisco", "cisco"),
    "00-05-73": ("Cisco", "cisco"),
    "00-05-74": ("Cisco", "cisco"),
    "00-05-9A": ("Cisco", "cisco"),
    "00-05-9B": ("Cisco", "cisco"),
    "00-05-DC": ("Cisco", "cisco"),
    "00-05-DD": ("Cisco", "cisco"),
    "00-06-28": ("Cisco", "cisco"),
    "00-06-2A": ("Cisco", "cisco"),
    "00-06-52": ("Cisco", "cisco"),
    "00-06-53": ("Cisco", "cisco"),
    "00-06-7C": ("Cisco", "cisco"),
    "00-06-D6": ("Cisco", "cisco"),
    "00-06-D7": ("Cisco", "cisco"),
    "00-06-F6": ("Cisco", "cisco"),
    "00-07-0D": ("Cisco", "cisco"),
    "00-07-0E": ("Cisco", "cisco"),
    "00-07-4F": ("Cisco", "cisco"),
    "00-07-50": ("Cisco", "cisco"),
    "00-07-7D": ("Cisco", "cisco"),
    "00-07-84": ("Cisco", "cisco"),
    "00-07-85": ("Cisco", "cisco"),
    "00-07-B3": ("Cisco", "cisco"),
    "00-07-B4": ("Cisco", "cisco"),
    "00-07-EB": ("Cisco", "cisco"),
    "00-07-EC": ("Cisco", "cisco"),
}


# =============================================================================
# SERVICE FINGERPRINTS - Port -> Device Type mapping
# =============================================================================

SERVICE_FINGERPRINTS = {
    # Streaming devices
    8008: ("chromecast", "streaming_device"),  # Chromecast
    8443: ("chromecast", "streaming_device"),  # Chromecast HTTPS
    9000: ("chromecast", "streaming_device"),  # Chromecast
    7000: ("airplay", "apple_tv"),  # AirPlay
    3689: ("daap", "apple_tv"),  # Apple DAAP
    
    # Smart TVs
    8001: ("samsung_tv", "smart_tv"),  # Samsung TV
    8002: ("samsung_tv", "smart_tv"),  # Samsung TV
    55000: ("samsung_tv", "smart_tv"),  # Samsung TV
    3000: ("lg_tv", "smart_tv"),  # LG TV
    3001: ("lg_tv", "smart_tv"),  # LG TV
    1925: ("roku", "streaming_device"),  # Roku
    8060: ("roku", "streaming_device"),  # Roku
    9080: ("roku", "streaming_device"),  # Roku
    
    # NAS devices
    5000: ("synology", "nas"),  # Synology DSM
    5001: ("synology_ssl", "nas"),  # Synology DSM SSL
    8080: ("qnap", "nas"),  # QNAP
    443: ("https", "server"),  # HTTPS
    
    # Network infrastructure
    53: ("dns", "router"),  # DNS
    67: ("dhcp", "router"),  # DHCP server
    161: ("snmp", "network"),  # SNMP
    
    # IoT/Smart Home
    1400: ("sonos", "speaker"),  # Sonos
    1443: ("sonos", "speaker"),  # Sonos
    6466: ("sonos", "speaker"),  # Sonos
    8082: ("ring", "camera"),  # Ring doorbell
    8883: ("mqtt_ssl", "iot"),  # MQTT SSL (IoT)
    1883: ("mqtt", "iot"),  # MQTT (IoT)
    
    # Gaming
    3074: ("xbox", "game_console"),  # Xbox Live
    3478: ("playstation", "game_console"),  # PlayStation
    3479: ("playstation", "game_console"),  # PlayStation
    3480: ("playstation", "game_console"),  # PlayStation
    
    # Cameras
    554: ("rtsp", "camera"),  # RTSP streaming
    80: ("http", "unknown"),  # HTTP
    8000: ("hikvision", "camera"),  # Hikvision
    37777: ("dahua", "camera"),  # Dahua
    
    # Printers
    9100: ("jetdirect", "printer"),  # JetDirect
    515: ("lpd", "printer"),  # LPD
    631: ("ipp", "printer"),  # IPP (CUPS)
    
    # Remote access
    22: ("ssh", "server"),  # SSH
    3389: ("rdp", "desktop"),  # RDP
    5900: ("vnc", "desktop"),  # VNC
}


# =============================================================================
# DEVICE TYPE CLASSIFICATION
# =============================================================================

VENDOR_TYPE_MAP = {
    # Streaming devices
    "roku": "streaming_device",
    "chromecast": "streaming_device",
    "google_nest": "smart_speaker",
    "fire_tv": "streaming_device",
    
    # Smart home
    "ring": "doorbell",
    "nest": "smart_thermostat",
    "philips_hue": "smart_light",
    "sonos": "smart_speaker",
    "wyze": "camera",
    "eufy": "camera",
    "hikvision": "camera",
    "dahua": "camera",
    
    # Network
    "cisco": "network",
    "ubiquiti": "access_point",
    "netgear": "router",
    "tp-link": "router",
    "asus": "router",
    
    # NAS
    "synology": "nas",
    "qnap": "nas",
    
    # Gaming
    "nintendo": "game_console",
    "playstation": "game_console",
    "xbox": "game_console",
    
    # Computing
    "vmware": "server",
    "microsoft": "desktop",
    "dell": "desktop",
    "hp": "desktop",
    "lenovo": "desktop",
    "intel": "desktop",
    "raspberry_pi": "server",
    
    # Mobile
    "apple": "mobile",
    "samsung": "mobile",
    "xiaomi": "mobile",
    "google": "mobile",
    
    # TV
    "lg": "smart_tv",
    "sony": "smart_tv",
    "amazon": "smart_device",
}


def get_vendor_from_mac(mac: str) -> tuple[str, str]:
    """Get vendor name and type key from MAC address."""
    if not mac or len(mac) < 8:
        return ("Unknown", "unknown")
    
    oui = mac[:8].upper().replace(":", "-")
    
    if oui in MAC_VENDORS:
        return MAC_VENDORS[oui]
    
    return ("Unknown", "unknown")


def classify_device(
    mac: str,
    ip: str,
    hostname: Optional[str] = None,
    open_ports: Optional[list[int]] = None,
    vendor_hint: Optional[str] = None,
) -> DeviceFingerprint:
    """
    Classify a device based on all available information.
    
    Args:
        mac: MAC address
        ip: IP address
        hostname: Optional hostname
        open_ports: List of open ports
        vendor_hint: Optional vendor hint from other sources
    
    Returns:
        DeviceFingerprint with device type and confidence
    """
    vendor, vendor_key = get_vendor_from_mac(mac)
    
    # Start with vendor-based classification
    device_type = VENDOR_TYPE_MAP.get(vendor_key, "unknown")
    confidence = 0.5 if device_type != "unknown" else 0.0
    services = []
    model = ""
    
    # Refine based on open ports
    if open_ports:
        for port in open_ports:
            if port in SERVICE_FINGERPRINTS:
                service, port_device_type = SERVICE_FINGERPRINTS[port]
                services.append(service)
                
                # Port-based type often more accurate
                if port_device_type != "unknown":
                    if device_type == "unknown" or device_type == "mobile":
                        device_type = port_device_type
                        confidence = max(confidence, 0.7)
    
    # Refine Apple devices
    if vendor_key == "apple":
        if open_ports:
            if 7000 in open_ports or 3689 in open_ports:
                device_type = "apple_tv"
                model = "Apple TV"
                confidence = 0.9
            elif 62078 in open_ports:  # iTunes sync
                device_type = "mobile"
                model = "iPhone/iPad"
                confidence = 0.8
        if hostname:
            hn = hostname.lower()
            if "iphone" in hn:
                device_type = "smartphone"
                model = "iPhone"
                confidence = 0.95
            elif "ipad" in hn:
                device_type = "tablet"
                model = "iPad"
                confidence = 0.95
            elif "macbook" in hn or "mac" in hn:
                device_type = "laptop"
                model = "Mac"
                confidence = 0.9
            elif "appletv" in hn or "apple-tv" in hn:
                device_type = "apple_tv"
                model = "Apple TV"
                confidence = 0.95
            elif "homepod" in hn:
                device_type = "smart_speaker"
                model = "HomePod"
                confidence = 0.95
    
    # Refine Samsung devices
    if vendor_key == "samsung":
        if open_ports:
            if 8001 in open_ports or 8002 in open_ports:
                device_type = "smart_tv"
                model = "Samsung TV"
                confidence = 0.9
        if hostname:
            hn = hostname.lower()
            if "tv" in hn or "samsung" in hn:
                device_type = "smart_tv"
                model = "Samsung TV"
                confidence = 0.85
            elif "galaxy" in hn or "sm-" in hn:
                device_type = "smartphone"
                model = "Samsung Galaxy"
                confidence = 0.9
    
    # Refine LG devices
    if vendor_key == "lg":
        if open_ports:
            if 3000 in open_ports or 3001 in open_ports:
                device_type = "smart_tv"
                model = "LG TV"
                confidence = 0.9
    
    # Refine Google devices
    if vendor_key == "google" or vendor_key == "google_nest":
        if open_ports:
            if 8008 in open_ports or 8443 in open_ports:
                device_type = "streaming_device"
                model = "Chromecast"
                confidence = 0.9
        if hostname:
            hn = hostname.lower()
            if "chromecast" in hn:
                device_type = "streaming_device"
                model = "Chromecast"
                confidence = 0.95
            elif "nest" in hn:
                device_type = "smart_speaker"
                model = "Google Nest"
                confidence = 0.9
            elif "home" in hn or "hub" in hn:
                device_type = "smart_speaker"
                model = "Google Home"
                confidence = 0.85
    
    # Refine Amazon devices
    if vendor_key == "amazon":
        if hostname:
            hn = hostname.lower()
            if "echo" in hn:
                device_type = "smart_speaker"
                model = "Amazon Echo"
                confidence = 0.95
            elif "fire" in hn:
                device_type = "streaming_device"
                model = "Fire TV"
                confidence = 0.9
        elif open_ports and 8443 in open_ports:
            device_type = "smart_speaker"
            model = "Amazon Echo"
            confidence = 0.7
    
    # Network devices by IP
    if ip.endswith(".1"):
        if device_type == "unknown" or device_type == "network":
            device_type = "router"
            confidence = max(confidence, 0.8)
    
    # Check hostname patterns
    if hostname:
        hn = hostname.lower()
        
        # Cameras
        if any(x in hn for x in ["camera", "cam", "ipcam", "nvr", "dvr"]):
            device_type = "camera"
            confidence = max(confidence, 0.85)
        
        # Printers
        if any(x in hn for x in ["printer", "print", "hp-", "epson", "canon", "brother"]):
            device_type = "printer"
            confidence = max(confidence, 0.9)
        
        # Servers
        if any(x in hn for x in ["server", "nas", "storage", "backup"]):
            device_type = "server"
            confidence = max(confidence, 0.8)
        
        # Access points
        if any(x in hn for x in ["ap-", "access", "unifi", "uap"]):
            device_type = "access_point"
            confidence = max(confidence, 0.85)
    
    return DeviceFingerprint(
        device_type=device_type,
        vendor=vendor,
        model=model,
        confidence=confidence,
        services=services,
    )


async def quick_port_scan(ip: str, ports: list[int] = None, timeout: float = 0.5) -> list[int]:
    """
    Quick port scan to identify device services.
    
    Args:
        ip: IP address to scan
        ports: List of ports to scan (defaults to common service ports)
        timeout: Timeout per port in seconds
    
    Returns:
        List of open ports
    """
    if ports is None:
        ports = [
            22, 53, 80, 443, 554, 631,  # Common services
            1400, 1883, 3000, 3001,  # Smart home
            5000, 5001, 5900,  # NAS, VNC
            7000, 8000, 8001, 8002, 8008, 8060, 8080, 8443,  # Streaming
            9000, 9100,  # Chromecast, printer
        ]
    
    open_ports = []
    
    async def check_port(port: int) -> Optional[int]:
        try:
            _, writer = await asyncio.wait_for(
                asyncio.open_connection(ip, port),
                timeout=timeout
            )
            writer.close()
            await writer.wait_closed()
            return port
        except (asyncio.TimeoutError, ConnectionRefusedError, OSError):
            return None
    
    # Scan ports concurrently
    tasks = [check_port(p) for p in ports]
    results = await asyncio.gather(*tasks, return_exceptions=True)
    
    for result in results:
        if isinstance(result, int):
            open_ports.append(result)
    
    return sorted(open_ports)


async def fingerprint_device(ip: str, mac: str, hostname: str = None) -> DeviceFingerprint:
    """
    Full device fingerprinting with port scanning.
    
    Args:
        ip: Device IP address
        mac: Device MAC address
        hostname: Optional hostname
    
    Returns:
        Complete DeviceFingerprint
    """
    # Quick port scan
    open_ports = await quick_port_scan(ip)
    
    # Classify
    return classify_device(
        mac=mac,
        ip=ip,
        hostname=hostname,
        open_ports=open_ports,
    )
